=begin
do $$
declare
rec record;
begin
for rec in (select bm.bank_code, bm.bank_name, bm.isactive, bm.swift_code, bm.local_bank, 
			bm.routing, bm.routing2, bde.valid_days from bank_master bm 
			left join bank_draft_expiry bde on bm.bank_code = bde.bank_code) loop
	raise notice '{code: "%", name: "%", status: "%", swift_code: "%", local_bank: %, routing: "%", routing2: "%", bank_draft_expiry_day: %}, ', 
	rec.bank_code, rec.bank_name, case when rec.isactive = 'Y' then 'ACTIVE' else 'INACTIVE' end, 
	coalesce(rec.swift_code, ''), case when rec.local_bank = 'Y' then 'true' else 'false' end, 
	coalesce(rec.routing, ''), coalesce(rec.routing2, ''), coalesce(rec.valid_days, 0);
end loop;
end;
$$;
=end

# banks
[
    {code: "AMB", name: "ARAB-MALAYSIAN BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 0}, 
    {code: "ABN", name: "ABN AMRO BANK", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "ABB", name: "ALLIED BANK (M) BHD", status: "INACTIVE", swift_code: "AGOBMYK1XXX", local_bank: true, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "AMBF", name: "AMBANK FINANCE", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 365}, 
    {code: "ABM", name: "ASEAM BANKERS MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BHL", name: "BAN HIN LEE BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BBMB", name: "BANK BUMIPUTRA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BBC", name: "BANK BUMIPUTRA COMMERCE BERHAD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BIM", name: "BANK INDUSTRI MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BKRB", name: "BANK KERJASAMA RAKYAT MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "100016020", routing2: "BKRB", bank_draft_expiry_day: 180}, 
    {code: "BPM", name: "BANK PERMBANGUNAN MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BPRM", name: "BANK PERTANIAN MALAYSIA", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BUB", name: "BANK UTAMA (M) BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BCB", name: "BUMIPUTRA-COMMERCE BANK BERHAD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "CKB", name: "CHUNG KHIAW BANK (M) BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BSN", name: "COMMERCIAL BANK (M) BHD", status: "INACTIVE", swift_code: "BSNAMYK1XXX", local_bank: true, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "DCB", name: "DCB BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "EON", name: "EON BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "EON", bank_draft_expiry_day: 180}, 
    {code: "EONCAP", name: "EONCAP ISLAMIC BANK BERHAD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "HHB", name: "HOCK HUA BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "HBM", name: "HONGKONG BANK MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "IBM", name: "INTERNATIONAL BANK MALAYSIA BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "LWB", name: "LEE WAH BANK", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "MPBB", name: "MULTI-PURPOSE BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "OBB", name: "ORIENTAL BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "OUB", name: "OVERSEAS UNION BANK (M) BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "PB", name: "PACIFIC BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "PAB", name: "PERWIRA AFFIN BANK", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "PA", name: "PHILEOALLIED BANK (M) BANK", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "RHBI", name: "RHB ISLAMIC BANK", status: "INACTIVE", swift_code: "", local_bank: false, routing: "100002186", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "SB", name: "SABAH BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "SIME", name: "SIME BANK BERHAD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "SBB", name: "SOUTHERN BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "WTB", name: "WAH TAT BANK BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BOC", name: "BANK OF COMMERCE (M) BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BOT", name: "BANK OF TOKYO (M) BHD", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "AFB", name: "AFFIN BANK BHD", status: "ACTIVE", swift_code: "PHBMMYKLXXX", local_bank: true, routing: "100002322", routing2: "AFB", bank_draft_expiry_day: 180}, 
    {code: "ARB", name: "AL RAJHI BANK", status: "ACTIVE", swift_code: "RJHIMYKLXXX", local_bank: true, routing: "100003509", routing2: "ARB", bank_draft_expiry_day: 180}, 
    {code: "ABMB", name: "ALLIANCE BANK MALAYSIA BERHAD", status: "ACTIVE", swift_code: "MFBBMYKLXXX", local_bank: true, routing: "100002128", routing2: "ABMB", bank_draft_expiry_day: 180}, 
    {code: "AIS", name: "ALLIANCE ISLAMIC BANK BERHAD", status: "ACTIVE", swift_code: "MFBBMYKLXXX", local_bank: true, routing: "100002128", routing2: "AIS", bank_draft_expiry_day: 180}, 
    {code: "AMBB", name: "AMBANK BERHAD", status: "ACTIVE", swift_code: "ARBKMYKLXXX", local_bank: true, routing: "100002089", routing2: "AMBB", bank_draft_expiry_day: 365}, 
    {code: "AMIBB", name: "AMISLAMIC BANK BERHAD", status: "ACTIVE", swift_code: "ARBKMYKLXXX", local_bank: true, routing: "100002089", routing2: "AMIBB", bank_draft_expiry_day: 365}, 
    {code: "AFBB", name: "ASIAN FINANCE BANK BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "", routing2: "AFBB", bank_draft_expiry_day: 180}, 
    {code: "BBB", name: "BANGKOK BANK BHD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "", routing2: "BBB", bank_draft_expiry_day: 180}, 
    {code: "BIMB", name: "BANK ISLAM MALAYSIA BHD", status: "ACTIVE", swift_code: "BIMBMYKLXXX", local_bank: true, routing: "100002458", routing2: "BIMB", bank_draft_expiry_day: 180}, 
    {code: "BMMB", name: "BANK MUAMALAT MALAYSIA BERHAD", status: "ACTIVE", swift_code: "BMMBMYKLXXX", local_bank: true, routing: "100003415", routing2: "BMMB", bank_draft_expiry_day: 180}, 
    {code: "BAM", name: "BANK OF AMERICA MALAYSIA BHD", status: "ACTIVE", swift_code: "BOFAMY2XXXX", local_bank: true, routing: "100002076", routing2: "BAM", bank_draft_expiry_day: 180}, 
    {code: "BCM", name: "BANK OF CHINA (MALAYSIA)BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "100002429", routing2: "BCM", bank_draft_expiry_day: 180}, 
    {code: "BNS", name: "BANK OF NOVA SCOTIA BHD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "", routing2: "BNS", bank_draft_expiry_day: 180}, 
    {code: "CIMB", name: "CIMB BANK BERHAD", status: "ACTIVE", swift_code: "CIBBMYKLXXX", local_bank: true, routing: "100002050", routing2: "CIMB", bank_draft_expiry_day: 180}, 
    {code: "CIMBI", name: "CIMB ISLAMIC", status: "ACTIVE", swift_code: "CIBBMYKLXXX", local_bank: true, routing: "100002050", routing2: "CIMBI", bank_draft_expiry_day: 180}, 
    {code: "CITI", name: "CITIBANK BHD", status: "ACTIVE", swift_code: "CITIMYKLXXX", local_bank: true, routing: "100002173", routing2: "CITI", bank_draft_expiry_day: 365}, 
    {code: "DBB", name: "DEUTSCHE BANK (M) BHD", status: "ACTIVE", swift_code: "DEUTMYKLXXX", local_bank: true, routing: "100002199", routing2: "DBB", bank_draft_expiry_day: 180}, 
    {code: "DUM", name: "DUMMY CODE FOR D/L/X REGN", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "FOC", name: "FOMEMA FOC", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "HLB", name: "HONG LEONG BANK BHD", status: "ACTIVE", swift_code: "HLBBMYKLXXX", local_bank: true, routing: "100002241", routing2: "HLB", bank_draft_expiry_day: 180}, 
    {code: "HLIB", name: "HONG LEONG ISLAMIC BANK", status: "ACTIVE", swift_code: "HLBBMYKLXXX", local_bank: true, routing: "100002241", routing2: "HLIB", bank_draft_expiry_day: 180}, 
    {code: "HSBC", name: "HONGKONG AND SHANGHAI BANK CORP.", status: "ACTIVE", swift_code: "HBMBMYKLXXX", local_bank: true, routing: "100002225", routing2: "HSBC", bank_draft_expiry_day: 360}, 
    {code: "CMB", name: "J.P.MORGAN CHASE BANK BERHAD", status: "ACTIVE", swift_code: "CHASMYKXXXX", local_bank: true, routing: "100002157", routing2: "CMB", bank_draft_expiry_day: 180}, 
    {code: "KFHMB", name: "KUWAIT FINANCE HOUSE (MALAYSIA) BERHAD", status: "ACTIVE", swift_code: "KFHOMYKLXXX", local_bank: true, routing: "100003460", routing2: "KFHMB", bank_draft_expiry_day: 180}, 
    {code: "MBB", name: "MAYBANK BHD", status: "ACTIVE", swift_code: "MBBEMYKLXXX", local_bank: true, routing: "100002270", routing2: "MBB", bank_draft_expiry_day: 180}, 
    {code: "MBI", name: "MAYBANK ISLAMIC", status: "ACTIVE", swift_code: "MBBEMYKLXXX", local_bank: true, routing: "100002270", routing2: "MBI", bank_draft_expiry_day: 180}, 
    {code: "PIS", name: "MBB DEPOSIT SLIPS", status: "ACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "OCBCAA", name: "OCBC AL-AMIN BANK BERHAD", status: "ACTIVE", swift_code: "OCBCMYKLXXX", local_bank: true, routing: "100002296", routing2: "OCBCAA", bank_draft_expiry_day: 90}, 
    {code: "OCBC", name: "OCBC BANK (M) BHD", status: "ACTIVE", swift_code: "OCBCMYKLXXX", local_bank: true, routing: "100002296", routing2: "OCBC", bank_draft_expiry_day: 180}, 
    {code: "POS", name: "POS MALAYSIA", status: "ACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "PMO", name: "POSTAL MONEY ORDER", status: "ACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 76}, 
    {code: "PBB", name: "PUBLIC BANK BHD", status: "ACTIVE", swift_code: "PBBEMYKLXXX", local_bank: true, routing: "100002335", routing2: "PBB", bank_draft_expiry_day: 180}, 
    {code: "PIB", name: "PUBLIC ISLAMIC BANK", status: "ACTIVE", swift_code: "PBBEMYKLXXX", local_bank: true, routing: "100002335", routing2: "PIB", bank_draft_expiry_day: 180}, 
    {code: "RHB", name: "RHB BANK BERHAD", status: "ACTIVE", swift_code: "RHBBMYKLXXX", local_bank: true, routing: "100002186", routing2: "RHB", bank_draft_expiry_day: 180}, 
    {code: "RHBIB", name: "RHB ISLAMIC BANK", status: "ACTIVE", swift_code: "RHBBMYKLXXX", local_bank: true, routing: "100002186", routing2: "RHBIB", bank_draft_expiry_day: 180}, 
    {code: "RBS", name: "ROYAL BANK OF SCOTLAND", status: "ACTIVE", swift_code: "ABNAMYKLXXX", local_bank: true, routing: "100002021", routing2: "RBS", bank_draft_expiry_day: 180}, 
    {code: "SCB", name: "STANDARD CHARTERED BANK MALAYSIA BHD", status: "ACTIVE", swift_code: "SCBLMYKXXXX", local_bank: true, routing: "100002144", routing2: "SCB", bank_draft_expiry_day: 180}, 
    {code: "UOB", name: "UNITED OVERSEAS BANK (M) BHD", status: "ACTIVE", swift_code: "UOVBMYKLXXX", local_bank: true, routing: "100002267", routing2: "UOB", bank_draft_expiry_day: 180}, 
    {code: "WPS", name: "WANG POS", status: "INACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "AIBB", name: "AFFIN ISLAMIC BANK BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "100002322", routing2: "AIBB", bank_draft_expiry_day: 180}, 
    {code: "HSBCAMB", name: "HSBC AMANAH MALAYSIA BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "100002225", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "SCSB", name: "STANDARD CHARTERED SAADIQ BERHAD", status: "ACTIVE", swift_code: "SCBLMYKXXXX", local_bank: true, routing: "100002144", routing2: "SCSB", bank_draft_expiry_day: 180}, 
    {code: "BNPPMB", name: "BNP PARIBAS MALAYSIA BERHAD", status: "ACTIVE", swift_code: "", local_bank: false, routing: "100002636", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "BTMUFJMB", name: "MUFG BANK (MALAYSIA) BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "100002102", routing2: "BOTM", bank_draft_expiry_day: 180}, 
    {code: "IIBMB", name: "INDIA INTERNATIONAL BANK (MALAYSIA) BERHAD", status: "ACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "ICBCMB", name: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BHD", status: "ACTIVE", swift_code: "", local_bank: false, routing: "100002597", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "MBMB", name: "MIZUHO BANK (MALAYSIA) BERHAD", status: "ACTIVE", swift_code: "", local_bank: false, routing: "100002610", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "NBADMB", name: "NATIONAL BANK OF ABU DHABI MALAYSIA BERHAD", status: "ACTIVE", swift_code: "", local_bank: false, routing: "", routing2: "", bank_draft_expiry_day: 180}, 
    {code: "SMBCMB", name: "SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BERHAD", status: "ACTIVE", swift_code: "", local_bank: true, routing: "100002623", routing2: "SUMITOMO", bank_draft_expiry_day: 180}, 
].each do |data|
    Bank.create!(data)
end
puts("banks seeded")
@banks = Bank.all