# Countries
[
    {old_code: 'BGR', code: 'BGR', name: 'BULGARIA'}, 
    {old_code: 'DJI', code: 'DJI', name: 'DJIBOUTI'}, 
    {old_code: 'BFA', code: 'BFA', name: 'BURKINA FASO'}, 
    {old_code: 'UNH', code: 'UNH', name: 'UNHCR'}, 
    {old_code: 'HUN', code: 'HUN', name: 'HUNGARY'}, 
    {old_code: 'MWI', code: 'MWI', name: 'MALAWI'}, 
    {old_code: 'PAL', code: 'PAL', name: 'PALESTINE'}, 
    {old_code: 'ZAM', code: 'ZMB', name: 'ZAMBIA'}, 
    {old_code: 'IRL', code: 'IRL', name: 'IRELAND'}, 
    {old_code: 'TJK', code: 'TJK', name: 'TAJIKISTAN'}, 
    {old_code: 'BEL', code: 'BEL', name: 'BELGIUM'}, 
    {old_code: 'DNK', code: 'DNK', name: 'DENMARK'}, 
    {old_code: 'NL', code: 'NLD', name: 'NETHERLANDS'}, 
    {old_code: 'NA', code: 'NAM', name: 'NAMIBIA'}, 
    {old_code: 'TKM', code: 'TKM', name: 'TURKMENISTAN'}, 
    {old_code: 'KEN', code: 'KEN', name: 'KENYA'}, 
    {old_code: 'USA', code: 'USA', name: 'USA'}, 
    {old_code: 'LSO', code: 'LSO', name: 'KINGDOM OF LESOTHO'}, 
    {old_code: 'CHL', code: 'CHL', name: 'CHILE'}, 
    {old_code: 'ESP', code: 'ESP', name: 'SPAIN'}, 
    {old_code: 'AFG', code: 'AFG', name: 'AFGHANISTAN'}, 
    {old_code: 'KH', code: 'KHM', name: 'CAMBODIA'}, 
    {old_code: 'ERI', code: 'ERI', name: 'ERITREA'}, 
    {old_code: 'EG', code: 'EGY', name: 'EGYPT'}, 
    {old_code: 'IR', code: 'IRN', name: 'IRAN'}, 
    {old_code: 'AU', code: 'AUS', name: 'AUSTRALIA'}, 
    {old_code: 'UZ', code: 'UZB', name: 'UZBEKISTAN'}, 
    {old_code: 'SO', code: 'SOM', name: 'SOMALIA'}, 
    {old_code: 'RU', code: 'RUS', name: 'RUSSIAN FEDERATION'}, 
    {old_code: 'KP', code: 'KHP', name: 'KAMPUCHEA'}, 
    {old_code: 'NP', code: 'NPL', name: 'NEPAL'}, 
    {old_code: 'SD', code: 'SDN', name: 'SUDAN'}, 
    {old_code: 'MA', code: 'MAR', name: 'MOROCCO'}, 
    {old_code: 'DZ', code: 'DZA', name: 'ALGERIA'}, 
    {old_code: 'AE', code: 'ARE', name: 'ARAB EMIRATES'}, 
    {old_code: 'BD', code: 'BGD', name: 'BANGLADESH'}, 
    {old_code: 'IN', code: 'IND', name: 'INDIA'}, 
    {old_code: 'PR', code: 'PER', name: 'PERU'}, 
    {old_code: 'TZ', code: 'TZA', name: 'TANZANIA'}, 
    {old_code: 'TN', code: 'TUN', name: 'TUNISIA'}, 
    {old_code: 'UG', code: 'UGA', name: 'UGANDA'}, 
    {old_code: 'ML', code: 'MLI', name: 'MALI'}, 
    {old_code: 'KG', code: 'KGZ', name: 'KYRGYZ'}, 
    {old_code: 'EC', code: 'ECU', name: 'ECUADOR'}, 
    {old_code: 'LB', code: 'LBN', name: 'LEBANON'}, 
    {old_code: 'NG', code: 'NGA', name: 'NIGERIA'}, 
    {old_code: 'GH', code: 'GHA', name: 'GHANA'}, 
    {old_code: 'VN', code: 'VNM', name: 'VIETNAM'}, 
    {old_code: 'TW', code: 'TWN', name: 'TAIWAN'}, 
    {old_code: 'KR', code: 'KOR', name: 'KOREA'}, 
    {old_code: 'JO', code: 'JOR', name: 'JORDAN'}, 
    {old_code: 'PN', code: 'PNG', name: 'PAPUA NEWGUINEA'}, 
    {old_code: 'TR', code: 'TUR', name: 'TURKEY'}, 
    {old_code: 'SYN', code: 'SYN', name: 'SYRIAN'}, 
    {old_code: 'DE', code: 'DGR', name: 'GERMANY'}, 
    {old_code: 'CH', code: 'CHE', name: 'SWITZERLAND'}, 
    {old_code: 'ET', code: 'ETH', name: 'ETHIOPIA'}, 
    {old_code: 'ID', code: 'IDN', name: 'INDONESIA'}, 
    {old_code: 'PH', code: 'PHL', name: 'PHILIPPINES'}, 
    {old_code: 'TH', code: 'THA', name: 'THAILAND'}, 
    {old_code: 'PK', code: 'PAK', name: 'PAKISTAN'}, 
    {old_code: 'LK', code: 'LKA', name: 'SRI LANKA'}, 
    {old_code: 'CN', code: 'CHN', name: 'CHINA'}, 
    {old_code: 'MM', code: 'MMR', name: 'MYANMAR'}, 
    {old_code: 'LA', code: 'LAO', name: 'LAOS'}, 
    {old_code: 'CO', code: 'COL', name: 'COLOMBIA'}, 
    {old_code: 'BN', code: 'BRN', name: 'BRUNEI DARUSSALAM'}, 
    {old_code: 'JP', code: 'JPN', name: 'JAPAN'}, 
    {old_code: 'IQ', code: 'IRQ', name: 'IRAQ'}, 
    {old_code: 'FJ', code: 'FJI', name: 'FIJI ISLANDS'}, 
    {old_code: 'SG', code: 'SGP', name: 'SINGAPORE'}, 
    {old_code: 'HK', code: 'HKG', name: 'HONG KONG'}, 
    {old_code: 'GBR', code: 'GBR', name: 'UNITED KINGDOM'}, 
    {old_code: 'AL', code: 'ALB', name: 'ALBANIA'}, 
    {old_code: 'MAD', code: 'MDG', name: 'MADAGASCAR'}, 
    {old_code: 'UKN', code: 'UKR', name: 'UKRAINE'}, 
    {old_code: 'DOM', code: 'DOM', name: 'DOMINICAN REPUBLIC'}, 
    {old_code: 'KA', code: 'KAZ', name: 'KAZAKHSTAN'}, 
    {old_code: 'VEN', code: 'VEN', name: 'VENEZUELA'}, 
    {old_code: 'GN', code: 'GIN', name: 'GUINEA'}, 
    {old_code: 'LY', code: 'LBY', name: 'LIBYA'}, 
    {old_code: 'SY', code: 'SYR', name: 'SYRIA'}, 
    {old_code: 'YE', code: 'YEM', name: 'YEMEN'}, 
    {old_code: 'ZW', code: 'ZWE', name: 'ZIMBABWE'}, 
    {old_code: 'BR', code: 'BRA', name: 'BRAZIL'}, 
    {old_code: 'GT', code: 'GTM', name: 'GUATEMALA'}, 
    {old_code: 'AZ', code: 'AZE', name: 'AZERBAIJAN'}, 
    {old_code: 'SWZ', code: 'SWZ', name: 'SWAZILAND'}, 
    {old_code: 'SA', code: 'ZAF', name: 'SOUTH AFRICA'}, 
    {old_code: 'SLB', code: 'SLB', name: 'SOLOMON ISLANDS'}, 
    {old_code: 'QTR', code: 'QAT', name: 'QATAR'}, 
    {old_code: 'CAN', code: 'CAN', name: 'CANADA'}, 
    {old_code: 'TP', code: 'TMP', name: 'TIMOR LESTE'}, 
    {old_code: 'SN', code: 'SEN', name: 'SENEGAL'}, 
    {old_code: 'CMR', code: 'CMR', name: 'CAMEROON'}, 
    {old_code: 'HR', code: 'HRV', name: 'CROATIA'}, 
    {old_code: 'FRA', code: 'FRA', name: 'FRANCE'}, 
    {old_code: 'GEO', code: 'GEO', name: 'GEORGIA'}, 
    {old_code: 'MY', code: 'MYS', name: 'MALAYSIA'}, 
    {old_code: 'MDV', code: 'MDV', name: 'MALDIVES'}, 
    {old_code: 'MX', code: 'MEX', name: 'MAXICO'}, 
    {old_code: 'CZE', code: 'CZE', name: 'CZECH REPUBLIC'}, 
    {old_code: 'MNG', code: 'MNG', name: 'MONGOLIA'}, 
    {old_code: 'BWA', code: 'BWA', name: 'BOTSWANA'}, 
    {old_code: 'BTN', code: 'BTN', name: 'BHUTAN'}, 
    {old_code: 'LIB', code: 'LIB', name: 'LIBERIA'}, 
    {old_code: 'HND', code: 'HND', name: 'REPUBLIC OF HONDURAS'}, 
    {old_code: 'SWE', code: 'SWE', name: 'SWEDEN'}, 
    {old_code: 'SLV', code: 'SLV', name: 'EL SALVADOR'}, 
    {old_code: 'NOR', code: 'NOR', name: 'NORWAY'}, 
    {old_code: 'ITA', code: 'ITA', name: 'ITALY'}, 
    {old_code: 'ISL', code: 'ISL', name: 'ICELAND'}
].each {|country_data| Country.create!(country_data)}

puts "countries seeded"
@malaysia = Country.find_by(code: Country::MALAYSIA_CODE)