[
    {code: 'REFUND_KT', category: 'REFUND', description: 'Refund GL Code - Kuala Terengganu', value: '322600303401'},
    {code: 'REFUND_SN', category: 'REFUND', description: 'Refund GL Code - Seremban', value: '322600303403'},
    {code: 'REFUND_AS', category: 'REFUND', description: 'Refund GL Code - Alor Setar', value: '322600303404'},
    {code: 'REFUND_IP', category: 'REFUND', description: 'Refund GL Code - Ipoh', value: '322600303406'},
    {code: 'REFUND_JB', category: 'REFUND', description: 'Refund GL Code - Johor Bahru', value: '322600303407'},
    {code: 'REFUND_KB', category: 'REFUND', description: 'Refund GL Code - Kota Bahru', value: '322600303408'},
    {code: 'REFUND_KN', category: 'REFUND', description: 'Refund GL Code - Kuantan', value: '322600303409'},
    {code: 'REFUND_MA', category: 'REFUND', description: 'Refund GL Code - Melaka', value: '322600303410'},
    {code: 'REFUND_PG', category: 'REFUND', description: 'Refund GL Code - Penang', value: '322600303412'},
    {code: 'REFUND_SA', category: 'REFUND', description: 'Refund GL Code - Shah Alam', value: '322600303413'},
    {code: 'REFUND_KL', category: 'REFUND', description: 'Refund GL Code - Kuala Lumpur', value: '322600303414'},
    {code: 'REFUND_PT', category: 'REFUND', description: 'Refund GL Code - Portal', value: '322600307421'},

    {code: 'COLLECTION_KT', category: 'COLLECTION', description: 'Collection GL Code - Kuala Terengganu', value: '322600303401'},
    {code: 'COLLECTION_SN', category: 'COLLECTION', description: 'Collection GL Code - Seremban', value: '322600303403'},
    {code: 'COLLECTION_AS', category: 'COLLECTION', description: 'Collection GL Code - Alor Setar', value: '322600303404'},
    {code: 'COLLECTION_IP', category: 'COLLECTION', description: 'Collection GL Code - Ipoh', value: '322600303406'},
    {code: 'COLLECTION_JB', category: 'COLLECTION', description: 'Collection GL Code - Johor Bahru', value: '322600303407'},
    {code: 'COLLECTION_KB', category: 'COLLECTION', description: 'Collection GL Code - Kota Bahru', value: '322600303408'},
    {code: 'COLLECTION_KN', category: 'COLLECTION', description: 'Collection GL Code - Kuantan', value: '322600303409'},
    {code: 'COLLECTION_MA', category: 'COLLECTION', description: 'Collection GL Code - Melaka', value: '322600303410'},
    {code: 'COLLECTION_PG', category: 'COLLECTION', description: 'Collection GL Code - Penang', value: '322600303412'},
    {code: 'COLLECTION_SA', category: 'COLLECTION', description: 'Collection GL Code - Shah Alam', value: '322600303413'},
    {code: 'COLLECTION_KL', category: 'COLLECTION', description: 'Collection GL Code - Kuala Lumpur', value: '322600303414'},
    {code: 'COLLECTION_PT', category: 'COLLECTION', description: 'Collection GL Code - Portal', value: '322600307421'},

    {code: 'COLLECTION_PT_CF', category: 'COLLECTION', description: 'Collection GL Code - Portal (Convenient Fee)', value: '619000307421'},
    {code: 'COLLECTION_PT_CF_BOLEHPAY', category: 'COLLECTION', description: 'Collection GL Code - Portal (Convenient Fee BolehPay)', value: '619001307421'},
    {code: 'COLLECTION_PT_INS', category: 'COLLECTION', description: 'Collection GL Code - Portal (Insurance)', value: '322601307421'},
    {code: 'COLLECTION_PT_AGENCY_REGIS', category: 'COLLECTION', description: 'Collection GL Code - Portal (Agency Registration)', value: '504000307421'},
    {code: 'COLLECTION_PT_AGENCY_RENEW', category: 'COLLECTION', description: 'Collection GL Code - Portal (Agency Renewal)', value: '504001307421'},

    {code: 'PAYMENT_DOCTOR_D_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Terengganu', value: '601200303401'},
    {code: 'PAYMENT_DOCTOR_D_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Terengganu', value: '601000303401'},
    {code: 'PAYMENT_DOCTOR_D_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Terengganu', value: '601300303401'},
    {code: 'PAYMENT_DOCTOR_D_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Terengganu', value: '601100303401'},
    {code: 'PAYMENT_DOCTOR_6_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Negeri Sembilan', value: '601200303403'},
    {code: 'PAYMENT_DOCTOR_6_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Negeri Sembilan', value: '601000303403'},
    {code: 'PAYMENT_DOCTOR_6_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Negeri Sembilan', value: '601300303403'},
    {code: 'PAYMENT_DOCTOR_6_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Negeri Sembilan', value: '601100303403'},
    {code: 'PAYMENT_DOCTOR_2_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Kedah', value: '601200303404'},
    {code: 'PAYMENT_DOCTOR_2_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Kedah', value: '601000303404'},
    {code: 'PAYMENT_DOCTOR_2_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Kedah', value: '601300303404'},
    {code: 'PAYMENT_DOCTOR_2_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Kedah', value: '601100303404'},
    {code: 'PAYMENT_DOCTOR_8_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Perak', value: '601200303406'},
    {code: 'PAYMENT_DOCTOR_8_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Perak', value: '601000303406'},
    {code: 'PAYMENT_DOCTOR_8_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Perak', value: '601300303406'},
    {code: 'PAYMENT_DOCTOR_8_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Perak', value: '601100303406'},
    {code: 'PAYMENT_DOCTOR_9_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Perlis', value: '601200303404'},
    {code: 'PAYMENT_DOCTOR_9_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Perlis', value: '601000303404'},
    {code: 'PAYMENT_DOCTOR_9_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Perlis', value: '601300303404'},
    {code: 'PAYMENT_DOCTOR_9_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Perlis', value: '601100303404'},
    {code: 'PAYMENT_DOCTOR_1_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Johor', value: '601200303407'},
    {code: 'PAYMENT_DOCTOR_1_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Johor', value: '601000303407'},
    {code: 'PAYMENT_DOCTOR_1_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Johor', value: '601300303407'},
    {code: 'PAYMENT_DOCTOR_1_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Johor', value: '601100303407'},
    {code: 'PAYMENT_DOCTOR_3_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Kelantan', value: '601200303408'},
    {code: 'PAYMENT_DOCTOR_3_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Kelantan', value: '601000303408'},
    {code: 'PAYMENT_DOCTOR_3_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Kelantan', value: '601300303408'},
    {code: 'PAYMENT_DOCTOR_3_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Kelantan', value: '601100303408'},
    {code: 'PAYMENT_DOCTOR_7_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Pahang', value: '601200303409'},
    {code: 'PAYMENT_DOCTOR_7_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Pahang', value: '601000303409'},
    {code: 'PAYMENT_DOCTOR_7_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Pahang', value: '601300303409'},
    {code: 'PAYMENT_DOCTOR_7_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Pahang', value: '601100303409'},
    {code: 'PAYMENT_DOCTOR_5_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Melaka', value: '601200303410'},
    {code: 'PAYMENT_DOCTOR_5_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Melaka', value: '601000303410'},
    {code: 'PAYMENT_DOCTOR_5_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Melaka', value: '601300303410'},
    {code: 'PAYMENT_DOCTOR_5_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Melaka', value: '601100303410'},
    {code: 'PAYMENT_DOCTOR_A_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Pulau Pinang', value: '601200303412'},
    {code: 'PAYMENT_DOCTOR_A_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Pulau Pinang', value: '601000303412'},
    {code: 'PAYMENT_DOCTOR_A_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Pulau Pinang', value: '601300303412'},
    {code: 'PAYMENT_DOCTOR_A_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Pulau Pinang', value: '601100303412'},
    {code: 'PAYMENT_DOCTOR_E_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Selangor', value: '601200303413'},
    {code: 'PAYMENT_DOCTOR_E_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Selangor', value: '601000303413'},
    {code: 'PAYMENT_DOCTOR_E_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Selangor', value: '601200303413'},
    {code: 'PAYMENT_DOCTOR_E_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Selangor', value: '601100303413'},
    {code: 'PAYMENT_DOCTOR_4_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Kuala Lumpur', value: '601200303414'},
    {code: 'PAYMENT_DOCTOR_4_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Kuala Lumpur', value: '601000303414'},
    {code: 'PAYMENT_DOCTOR_4_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Kuala Lumpur', value: '601300303414'},
    {code: 'PAYMENT_DOCTOR_4_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Kuala Lumpur', value: '601100303414'},
    {code: 'PAYMENT_DOCTOR_F_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Putrajaya', value: '601200303414'},
    {code: 'PAYMENT_DOCTOR_F_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Putrajaya', value: '601000303414'},
    {code: 'PAYMENT_DOCTOR_F_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Putrajaya', value: '601300303414'},
    {code: 'PAYMENT_DOCTOR_F_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Putrajaya', value: '601100303414'},
    {code: 'PAYMENT_DOCTOR_G_M_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Group - Labuan', value: '601200303402'},
    {code: 'PAYMENT_DOCTOR_G_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Male Non-Group - Labuan', value: '601000303402'},
    {code: 'PAYMENT_DOCTOR_G_F_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Group - Labuan', value: '601300303402'},
    {code: 'PAYMENT_DOCTOR_G_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Doctor GL Code For Female Non-Group - Labuan', value: '601100303402'},

    {code: 'PAYMENT_XRAYFACILITY_D_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Terengganu', value: '602200303401'},
    {code: 'PAYMENT_XRAYFACILITY_D_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Terengganu', value: '602000303401'},
    {code: 'PAYMENT_XRAYFACILITY_D_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Terengganu', value: '602300303401'},
    {code: 'PAYMENT_XRAYFACILITY_D_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Terengganu', value: '602100303401'},
    {code: 'PAYMENT_XRAYFACILITY_6_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Negeri Sembilan', value: '602200303403'},
    {code: 'PAYMENT_XRAYFACILITY_6_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Negeri Sembilan', value: '602000303403'},
    {code: 'PAYMENT_XRAYFACILITY_6_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Negeri Sembilan', value: '602300303403'},
    {code: 'PAYMENT_XRAYFACILITY_6_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Negeri Sembilan', value: '602100303403'},
    {code: 'PAYMENT_XRAYFACILITY_2_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Kedah', value: '602200303404'},
    {code: 'PAYMENT_XRAYFACILITY_2_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Kedah', value: '602000303404'},
    {code: 'PAYMENT_XRAYFACILITY_2_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Kedah', value: '602300303404'},
    {code: 'PAYMENT_XRAYFACILITY_2_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Kedah', value: '602100303404'},
    {code: 'PAYMENT_XRAYFACILITY_8_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Perak', value: '602200303406'},
    {code: 'PAYMENT_XRAYFACILITY_8_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Perak', value: '602000303406'},
    {code: 'PAYMENT_XRAYFACILITY_8_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Perak', value: '602300303406'},
    {code: 'PAYMENT_XRAYFACILITY_8_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Perak', value: '602100303406'},
    {code: 'PAYMENT_XRAYFACILITY_9_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Perlis', value: '602200303404'},
    {code: 'PAYMENT_XRAYFACILITY_9_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Perlis', value: '602000303404'},
    {code: 'PAYMENT_XRAYFACILITY_9_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Perlis', value: '602300303404'},
    {code: 'PAYMENT_XRAYFACILITY_9_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Perlis', value: '602100303404'},
    {code: 'PAYMENT_XRAYFACILITY_1_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Johor', value: '602200303407'},
    {code: 'PAYMENT_XRAYFACILITY_1_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Johor', value: '602000303407'},
    {code: 'PAYMENT_XRAYFACILITY_1_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Johor', value: '602300303407'},
    {code: 'PAYMENT_XRAYFACILITY_1_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Johor', value: '602100303407'},
    {code: 'PAYMENT_XRAYFACILITY_3_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Kelantan', value: '602200303408'},
    {code: 'PAYMENT_XRAYFACILITY_3_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Kelantan', value: '602000303408'},
    {code: 'PAYMENT_XRAYFACILITY_3_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Kelantan', value: '602300303408'},
    {code: 'PAYMENT_XRAYFACILITY_3_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Kelantan', value: '602100303408'},
    {code: 'PAYMENT_XRAYFACILITY_7_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Pahang', value: '602200303409'},
    {code: 'PAYMENT_XRAYFACILITY_7_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Pahang', value: '602000303409'},
    {code: 'PAYMENT_XRAYFACILITY_7_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Pahang', value: '602300303409'},
    {code: 'PAYMENT_XRAYFACILITY_7_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Pahang', value: '602100303409'},
    {code: 'PAYMENT_XRAYFACILITY_5_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Melaka', value: '602200303410'},
    {code: 'PAYMENT_XRAYFACILITY_5_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Melaka', value: '602000303410'},
    {code: 'PAYMENT_XRAYFACILITY_5_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Melaka', value: '602300303410'},
    {code: 'PAYMENT_XRAYFACILITY_5_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Melaka', value: '602100303410'},
    {code: 'PAYMENT_XRAYFACILITY_A_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Pulau Pinang', value: '602200303412'},
    {code: 'PAYMENT_XRAYFACILITY_A_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Pulau Pinang', value: '602000303412'},
    {code: 'PAYMENT_XRAYFACILITY_A_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Pulau Pinang', value: '602300303412'},
    {code: 'PAYMENT_XRAYFACILITY_A_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Pulau Pinang', value: '602100303412'},
    {code: 'PAYMENT_XRAYFACILITY_E_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Selangor', value: '602200303413'},
    {code: 'PAYMENT_XRAYFACILITY_E_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Selangor', value: '602000303413'},
    {code: 'PAYMENT_XRAYFACILITY_E_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Selangor', value: '602200303413'},
    {code: 'PAYMENT_XRAYFACILITY_E_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Selangor', value: '602100303413'},
    {code: 'PAYMENT_XRAYFACILITY_4_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Kuala Lumpur', value: '602200303414'},
    {code: 'PAYMENT_XRAYFACILITY_4_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Kuala Lumpur', value: '602000303414'},
    {code: 'PAYMENT_XRAYFACILITY_4_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Kuala Lumpur', value: '602300303414'},
    {code: 'PAYMENT_XRAYFACILITY_4_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Kuala Lumpur', value: '602100303414'},
    {code: 'PAYMENT_XRAYFACILITY_F_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Putrajaya', value: '602200303414'},
    {code: 'PAYMENT_XRAYFACILITY_F_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Putrajaya', value: '602000303414'},
    {code: 'PAYMENT_XRAYFACILITY_F_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Putrajaya', value: '602300303414'},
    {code: 'PAYMENT_XRAYFACILITY_F_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Putrajaya', value: '602100303414'},
    {code: 'PAYMENT_XRAYFACILITY_G_M_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Group - Labuan', value: '602200303402'},
    {code: 'PAYMENT_XRAYFACILITY_G_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Male Non-Group - Labuan', value: '602000303402'},
    {code: 'PAYMENT_XRAYFACILITY_G_F_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Group - Labuan', value: '602300303402'},
    {code: 'PAYMENT_XRAYFACILITY_G_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Xray GL Code For Female Non-Group - Labuan', value: '602100303402'},

    {code: 'PAYMENT_LABORATORY_D_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Terengganu', value: '603200303401'},
    {code: 'PAYMENT_LABORATORY_D_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Terengganu', value: '603000303401'},
    {code: 'PAYMENT_LABORATORY_D_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Terengganu', value: '603300303401'},
    {code: 'PAYMENT_LABORATORY_D_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Terengganu', value: '603100303401'},
    {code: 'PAYMENT_LABORATORY_6_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Negeri Sembilan', value: '603200303403'},
    {code: 'PAYMENT_LABORATORY_6_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Negeri Sembilan', value: '603000303403'},
    {code: 'PAYMENT_LABORATORY_6_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Negeri Sembilan', value: '603300303403'},
    {code: 'PAYMENT_LABORATORY_6_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Negeri Sembilan', value: '603100303403'},
    {code: 'PAYMENT_LABORATORY_2_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Kedah', value: '603200303404'},
    {code: 'PAYMENT_LABORATORY_2_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Kedah', value: '603000303404'},
    {code: 'PAYMENT_LABORATORY_2_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Kedah', value: '603300303404'},
    {code: 'PAYMENT_LABORATORY_2_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Kedah', value: '603100303404'},
    {code: 'PAYMENT_LABORATORY_8_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Perak', value: '603200303406'},
    {code: 'PAYMENT_LABORATORY_8_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Perak', value: '603000303406'},
    {code: 'PAYMENT_LABORATORY_8_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Perak', value: '603300303406'},
    {code: 'PAYMENT_LABORATORY_8_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Perak', value: '603100303406'},
    {code: 'PAYMENT_LABORATORY_9_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Perlis', value: '603200303404'},
    {code: 'PAYMENT_LABORATORY_9_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Perlis', value: '603000303404'},
    {code: 'PAYMENT_LABORATORY_9_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Perlis', value: '603300303404'},
    {code: 'PAYMENT_LABORATORY_9_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Perlis', value: '603100303404'},
    {code: 'PAYMENT_LABORATORY_1_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Johor', value: '603200303407'},
    {code: 'PAYMENT_LABORATORY_1_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Johor', value: '603000303407'},
    {code: 'PAYMENT_LABORATORY_1_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Johor', value: '603300303407'},
    {code: 'PAYMENT_LABORATORY_1_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Johor', value: '603100303407'},
    {code: 'PAYMENT_LABORATORY_3_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Kelantan', value: '603200303408'},
    {code: 'PAYMENT_LABORATORY_3_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Kelantan', value: '603000303408'},
    {code: 'PAYMENT_LABORATORY_3_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Kelantan', value: '603300303408'},
    {code: 'PAYMENT_LABORATORY_3_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Kelantan', value: '603100303408'},
    {code: 'PAYMENT_LABORATORY_7_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Pahang', value: '603200303409'},
    {code: 'PAYMENT_LABORATORY_7_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Pahang', value: '603000303409'},
    {code: 'PAYMENT_LABORATORY_7_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Pahang', value: '603300303409'},
    {code: 'PAYMENT_LABORATORY_7_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Pahang', value: '603100303409'},
    {code: 'PAYMENT_LABORATORY_5_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Melaka', value: '603200303410'},
    {code: 'PAYMENT_LABORATORY_5_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Melaka', value: '603000303410'},
    {code: 'PAYMENT_LABORATORY_5_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Melaka', value: '603300303410'},
    {code: 'PAYMENT_LABORATORY_5_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Melaka', value: '603100303410'},
    {code: 'PAYMENT_LABORATORY_A_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Pulau Pinang', value: '603200303412'},
    {code: 'PAYMENT_LABORATORY_A_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Pulau Pinang', value: '603000303412'},
    {code: 'PAYMENT_LABORATORY_A_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Pulau Pinang', value: '603300303412'},
    {code: 'PAYMENT_LABORATORY_A_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Pulau Pinang', value: '603100303412'},
    {code: 'PAYMENT_LABORATORY_E_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Selangor', value: '603200303413'},
    {code: 'PAYMENT_LABORATORY_E_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Selangor', value: '603000303413'},
    {code: 'PAYMENT_LABORATORY_E_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Selangor', value: '603200303413'},
    {code: 'PAYMENT_LABORATORY_E_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Selangor', value: '603100303413'},
    {code: 'PAYMENT_LABORATORY_4_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Kuala Lumpur', value: '603200303414'},
    {code: 'PAYMENT_LABORATORY_4_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Kuala Lumpur', value: '603000303414'},
    {code: 'PAYMENT_LABORATORY_4_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Kuala Lumpur', value: '603300303414'},
    {code: 'PAYMENT_LABORATORY_4_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Kuala Lumpur', value: '603100303414'},
    {code: 'PAYMENT_LABORATORY_F_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Putrajaya', value: '603200303414'},
    {code: 'PAYMENT_LABORATORY_F_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Putrajaya', value: '603000303414'},
    {code: 'PAYMENT_LABORATORY_F_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Putrajaya', value: '603300303414'},
    {code: 'PAYMENT_LABORATORY_F_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Putrajaya', value: '603100303414'},
    {code: 'PAYMENT_LABORATORY_G_M_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Group - Labuan', value: '603200303402'},
    {code: 'PAYMENT_LABORATORY_G_M_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Male Non-Group - Labuan', value: '603000303402'},
    {code: 'PAYMENT_LABORATORY_G_F_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Group - Labuan', value: '603300303402'},
    {code: 'PAYMENT_LABORATORY_G_F_NON_GROUP', category: 'PAYMENT', description: 'Payment Laboratory GL Code For Female Non-Group - Labuan', value: '603100303402'},

    {code: 'REVENUE_REG_KT_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Kuala Terengganu', value: '326200303401'},
    {code: 'REVENUE_REG_SN_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Seremban', value: '326200303403'},
    {code: 'REVENUE_REG_AS_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Alor Setar', value: '326200303404'},
    {code: 'REVENUE_REG_IP_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Ipoh', value: '326200303406'},
    {code: 'REVENUE_REG_JB_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Johor Bahru', value: '326200303407'},
    {code: 'REVENUE_REG_KB_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Kota Bahru', value: '326200303408'},
    {code: 'REVENUE_REG_KN_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Kuantan', value: '326200303409'},
    {code: 'REVENUE_REG_MA_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Melaka', value: '326200303410'},
    {code: 'REVENUE_REG_PG_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Penang', value: '326200303412'},
    {code: 'REVENUE_REG_SA_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Shah Alam', value: '326200303413'},
    {code: 'REVENUE_REG_KL_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Kuala Lumpur', value: '326200303414'},
    {code: 'REVENUE_REG_PT_M', category: 'REVENUE', description: 'Revenue Registration GL Code For Male - Portal', value: '326200307421'},

    {code: 'REVENUE_REG_KT_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Kuala Terengganu', value: '326300303401'},
    {code: 'REVENUE_REG_SN_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Seremban', value: '326300303403'},
    {code: 'REVENUE_REG_AS_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Alor Setar', value: '326300303404'},
    {code: 'REVENUE_REG_IP_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Ipoh', value: '326300303406'},
    {code: 'REVENUE_REG_JB_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Johor Bahru', value: '326300303407'},
    {code: 'REVENUE_REG_KB_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Kota Bahru', value: '326300303408'},
    {code: 'REVENUE_REG_KN_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Kuantan', value: '326300303409'},
    {code: 'REVENUE_REG_MA_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Melaka', value: '326300303410'},
    {code: 'REVENUE_REG_PG_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Penang', value: '326300303412'},
    {code: 'REVENUE_REG_SA_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Shah Alam', value: '326300303413'},
    {code: 'REVENUE_REG_KL_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Kuala Lumpur', value: '326300303414'},
    {code: 'REVENUE_REG_PT_F', category: 'REVENUE', description: 'Revenue Registration GL Code For Female - Portal', value: '326300307421'},

    {code: 'REVENUE_CERT_KT_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Kuala Terengganu', value: '501000303401'},
    {code: 'REVENUE_CERT_SN_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Seremban', value: '501000303403'},
    {code: 'REVENUE_CERT_AS_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Alor Setar', value: '501000303404'},
    {code: 'REVENUE_CERT_IP_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Ipoh', value: '501000303406'},
    {code: 'REVENUE_CERT_JB_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Johor Bahru', value: '501000303407'},
    {code: 'REVENUE_CERT_KB_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Kota Bahru', value: '501000303408'},
    {code: 'REVENUE_CERT_KN_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Kuantan', value: '501000303409'},
    {code: 'REVENUE_CERT_MA_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Melaka', value: '501000303410'},
    {code: 'REVENUE_CERT_PG_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Penang', value: '501000303412'},
    {code: 'REVENUE_CERT_SA_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Shah Alam', value: '501000303413'},
    {code: 'REVENUE_CERT_KL_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Kuala Lumpur', value: '501000303414'},
    {code: 'REVENUE_CERT_PT_M', category: 'REVENUE', description: 'Revenue Certification GL Code For Male - Portal', value: '501000307421'},

    {code: 'REVENUE_CERT_KT_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Kuala Terengganu', value: '501100303401'},
    {code: 'REVENUE_CERT_SN_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Seremban', value: '501100303403'},
    {code: 'REVENUE_CERT_AS_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Alor Setar', value: '501100303404'},
    {code: 'REVENUE_CERT_IP_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Ipoh', value: '501100303406'},
    {code: 'REVENUE_CERT_JB_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Johor Bahru', value: '501100303407'},
    {code: 'REVENUE_CERT_KB_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Kota Bahru', value: '501100303408'},
    {code: 'REVENUE_CERT_KN_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Kuantan', value: '501100303409'},
    {code: 'REVENUE_CERT_MA_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Melaka', value: '501100303410'},
    {code: 'REVENUE_CERT_PG_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Penang', value: '501100303412'},
    {code: 'REVENUE_CERT_SA_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Shah Alam', value: '501100303413'},
    {code: 'REVENUE_CERT_KL_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Kuala Lumpur', value: '501100303414'},
    {code: 'REVENUE_CERT_PT_F', category: 'REVENUE', description: 'Revenue Certification GL Code For Female - Portal', value: '501100307421'},

    {code: 'REVENUE_WC_KT', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Kuala Terengganu', value: '620100303401'},
    {code: 'REVENUE_WC_SN', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Seremban', value: '620100303403'},
    {code: 'REVENUE_WC_AS', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Alor Setar', value: '620100303404'},
    {code: 'REVENUE_WC_IP', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Ipoh', value: '620100303406'},
    {code: 'REVENUE_WC_JB', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Johor Bahru', value: '620100303407'},
    {code: 'REVENUE_WC_KB', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Kota Bahru', value: '620100303408'},
    {code: 'REVENUE_WC_KN', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Kuantan', value: '620100303409'},
    {code: 'REVENUE_WC_MA', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Melaka', value: '620100303410'},
    {code: 'REVENUE_WC_PG', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Penang', value: '620100303412'},
    {code: 'REVENUE_WC_SA', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Shah Alam', value: '620100303413'},
    {code: 'REVENUE_WC_KL', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Kuala Lumpur', value: '620100303414'},
    {code: 'REVENUE_WC_PT', category: 'REVENUE', description: 'Revenue Worker Cancellation GL Code - Portal', value: '620100307421'},

    {code: 'REVENUE_RM_KT', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Kuala Terengganu', value: '620200303401'},
    {code: 'REVENUE_RM_SN', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Seremban', value: '620200303403'},
    {code: 'REVENUE_RM_AS', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Alor Setar', value: '620200303404'},
    {code: 'REVENUE_RM_IP', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Ipoh', value: '620200303406'},
    {code: 'REVENUE_RM_JB', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Johor Bahru', value: '620200303407'},
    {code: 'REVENUE_RM_KB', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Kota Bahru', value: '620200303408'},
    {code: 'REVENUE_RM_KN', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Kuantan', value: '620200303409'},
    {code: 'REVENUE_RM_MA', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Melaka', value: '620200303410'},
    {code: 'REVENUE_RM_PG', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Penang', value: '620200303412'},
    {code: 'REVENUE_RM_SA', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Shah Alam', value: '620200303413'},
    {code: 'REVENUE_RM_KL', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Kuala Lumpur', value: '620200303414'},
    {code: 'REVENUE_RM_PT', category: 'REVENUE', description: 'Revenue Reprint Medical Form GL Code - Portal', value: '620200307421'},

    {code: 'REVENUE_CD_KT', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Kuala Terengganu', value: '620300303401'},
    {code: 'REVENUE_CD_SN', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Seremban', value: '620300303403'},
    {code: 'REVENUE_CD_AS', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Alor Setar', value: '620300303404'},
    {code: 'REVENUE_CD_IP', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Ipoh', value: '620300303406'},
    {code: 'REVENUE_CD_JB', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Johor Bahru', value: '620300303407'},
    {code: 'REVENUE_CD_KB', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Kota Bahru', value: '620300303408'},
    {code: 'REVENUE_CD_KN', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Kuantan', value: '620300303409'},
    {code: 'REVENUE_CD_MA', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Melaka', value: '620300303410'},
    {code: 'REVENUE_CD_PG', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Penang', value: '620300303412'},
    {code: 'REVENUE_CD_SA', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Shah Alam', value: '620300303413'},
    {code: 'REVENUE_CD_KL', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Kuala Lumpur', value: '620300303414'},
    {code: 'REVENUE_CD_PT', category: 'REVENUE', description: 'Revenue Change Doctor GL Code - Portal', value: '620300307421'},

    {code: 'REVENUE_WA_KT', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Kuala Terengganu', value: '620500303401'},
    {code: 'REVENUE_WA_SN', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Seremban', value: '620500303403'},
    {code: 'REVENUE_WA_AS', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Alor Setar', value: '620500303404'},
    {code: 'REVENUE_WA_IP', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Ipoh', value: '620500303406'},
    {code: 'REVENUE_WA_JB', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Johor Bahru', value: '620500303407'},
    {code: 'REVENUE_WA_KB', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Kota Bahru', value: '620500303408'},
    {code: 'REVENUE_WA_KN', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Kuantan', value: '620500303409'},
    {code: 'REVENUE_WA_MA', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Melaka', value: '620500303410'},
    {code: 'REVENUE_WA_PG', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Penang', value: '620500303412'},
    {code: 'REVENUE_WA_SA', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Shah Alam', value: '620500303413'},
    {code: 'REVENUE_WA_KL', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Kuala Lumpur', value: '620500303414'},
    {code: 'REVENUE_WA_PT', category: 'REVENUE', description: 'Revenue Worker Amendment GL Code - Portal', value: '620500307421'},

    {code: 'REVENUE_CG_KT', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Kuala Terengganu', value: '620600303401'},
    {code: 'REVENUE_CG_SN', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Seremban', value: '620600303403'},
    {code: 'REVENUE_CG_AS', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Alor Setar', value: '620600303404'},
    {code: 'REVENUE_CG_IP', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Ipoh', value: '620600303406'},
    {code: 'REVENUE_CG_JB', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Johor Bahru', value: '620600303407'},
    {code: 'REVENUE_CG_KB', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Kota Bahru', value: '620600303408'},
    {code: 'REVENUE_CG_KN', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Kuantan', value: '620600303409'},
    {code: 'REVENUE_CG_MA', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Melaka', value: '620600303410'},
    {code: 'REVENUE_CG_PG', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Penang', value: '620600303412'},
    {code: 'REVENUE_CG_SA', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Shah Alam', value: '620600303413'},
    {code: 'REVENUE_CG_KL', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Kuala Lumpur', value: '620600303414'},
    {code: 'REVENUE_CG_PT', category: 'REVENUE', description: 'Revenue Change Gender GL Code - Portal', value: '620600307421'},

    {code: 'REVENUE_TE_KT', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Kuala Terengganu', value: '620700303401'},
    {code: 'REVENUE_TE_SN', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Seremban', value: '620700303403'},
    {code: 'REVENUE_TE_AS', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Alor Setar', value: '620700303404'},
    {code: 'REVENUE_TE_IP', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Ipoh', value: '620700303406'},
    {code: 'REVENUE_TE_JB', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Johor Bahru', value: '620700303407'},
    {code: 'REVENUE_TE_KB', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Kota Bahru', value: '620700303408'},
    {code: 'REVENUE_TE_KN', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Kuantan', value: '620700303409'},
    {code: 'REVENUE_TE_MA', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Melaka', value: '620700303410'},
    {code: 'REVENUE_TE_PG', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Penang', value: '620700303412'},
    {code: 'REVENUE_TE_SA', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Shah Alam', value: '620700303413'},
    {code: 'REVENUE_TE_KL', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Kuala Lumpur', value: '620700303414'},
    {code: 'REVENUE_TE_PT', category: 'REVENUE', description: 'Revenue Transaction Extent GL Code - Portal', value: '620700307421'},

    {code: 'REVENUE_REG_DOCTOR', category: 'REVENUE', description: 'Revenue Registration(Doctor) GL Code', value: '503000314411'},
    {code: 'REVENUE_REG_XRAYFACILITY', category: 'REVENUE', description: 'Revenue Registration(X-ray Facility) GL Code', value: '507000314411'},
    {code: 'REVENUE_REG_LABORATORY', category: 'REVENUE', description: 'Revenue Registration(Laboratory) GL Code', value: '506000314411'},
    {code: 'REVENUE_REG_RADIOLOGIST', category: 'REVENUE', description: 'Revenue Registration(Radiologist) GL Code', value: '508000314411'},
    {code: 'REVENUE_CHANGE_CLINIC_ADDRESS', category: 'REVENUE', description: 'Revenue Change Clinic Address GL Code', value: '509000314411'},
    {code: 'REVENUE_BIOMETRIC_DEVICE', category: 'REVENUE', description: 'Revenue Biometric Device GL Code', value: '222000000000'},
    {code: 'REVENUE_BIOMETRIC_ADMIN', category: 'REVENUE', description: 'Revenue Biometric Admin and Deployment GL Code', value: '611400314411'},

    {code: 'REVENUE_SFSREG_PT', category: 'REVENUE', description: 'Revenue Special Renewal Rejected fee GL Code - Portal', value: '620800307421'},

    {code: 'BANK_OCBC_KT', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Kuala Terengganu', value: 'OCBCKT', bank_number: '1041022732'},
    {code: 'BANK_OCBC_SN', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Seremban', value: 'OCBCSN', bank_number: '1041022724'},
    {code: 'BANK_OCBC_AS', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Alor Setar', value: 'OCBCAS', bank_number: '1041022708'},
    {code: 'BANK_OCBC_IP', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Ipoh', value: 'OCBCIP', bank_number: '1041022740'},
    {code: 'BANK_OCBC_JB', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Johor Bahru', value: 'OCBCJB', bank_number: '1041022678'},
    {code: 'BANK_OCBC_KB', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Kota Bahru', value: 'OCBCKB', bank_number: '1041022651'},
    {code: 'BANK_OCBC_KN', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Kuantan', value: 'OCBCKN', bank_number: '1041022694'},
    {code: 'BANK_OCBC_MA', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Melaka', value: 'OCBCMA', bank_number: '1041022686'},
    {code: 'BANK_OCBC_PG', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Penang', value: 'OCBCPG', bank_number: '1041022716'},
    {code: 'BANK_OCBC_SA', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Shah Alam', value: 'OCBCSA', bank_number: '1041022775'},
    {code: 'BANK_OCBC_KL', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Kuala Lumpur', value: 'OCBCKL', bank_number: '1041022767'},

    {code: 'BANK_OCBC_MAIN', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Ampang - Ipay88, PBB (Debit Card/Credit Card)', value: 'OCBCAM', bank_number: '1041021922'},
    {code: 'BANK_OCBC_PT', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Portal', value: 'OCBCAM', bank_number: '1041021922'},
    {code: 'BANK_OCBC_OTHER', category: 'BANK', description: 'Bank OCBC - Miscellaneous Collection (Unsuitable slip, cash advance refund, Doctor New Registration, etc)', value: 'OCBCOI', bank_number: '1041022864'},
    {code: 'BANK_OCBC_DOCTOR', category: 'BANK', description: 'Bank OCBC - Doctor Payment', value: 'OCBCDX', bank_number: '1041022872'},
    {code: 'BANK_OCBC_XRAYFACILITY', category: 'BANK', description: 'Bank OCBC - Xray Payment', value: 'OCBCDX', bank_number: '1041022872'},
    {code: 'BANK_OCBC_LABORATORY', category: 'BANK', description: 'Bank OCBC - Laboratory Payment', value: 'OCBCLA', bank_number: '1041022880'},

    {code: 'BANK_CIMB', category: 'BANK', description: 'Bank CIMB - FW Registration Collection', value: 'CIMB648'},

    {code: 'BANK_OCBC_PT_SWIPE', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Portal (SWIPE)', value: 'OCBCFPX', bank_number: ''},
    {code: 'BANK_OCBC_PT_PAYNET', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Portal (PAYNET)', value: 'OCBCAM', bank_number: ''},
    {code: 'BANK_OCBC_PT_BOLEH', category: 'BANK', description: 'Bank OCBC - FW Registration Collection - Portal (BOLEHPAY)', value: 'OCBCAM', bank_number: ''},

    {code: 'GROUP_DOCTOR', category: 'GROUP', description: 'Group Doctor - Use by finance system', value: 'TRDMED'},
    {code: 'GROUP_XRAYFACILITY', category: 'GROUP', description: 'Group Xray - Use by finance system', value: 'TRDXRY'},
    {code: 'GROUP_LABORATORY', category: 'GROUP', description: 'Group Laboratory - Use by finance system', value: 'TRDLAB'},
    {code: 'GROUP_EMPLOYER', category: 'GROUP', description: 'Group Employer - Use by finance system', value: 'REFUND'},
    {code: 'GROUP_AGENCY', category: 'GROUP', description: 'Group Agency - Use by finance system', value: 'REFUND'},

    {code: 'SOURCE_TYPE_REG', category: 'SOURCE_TYPE', description: 'Source Type - Worker Registration', value: 'NS'},
    {code: 'SOURCE_TYPE_CERT', category: 'SOURCE_TYPE', description: 'Source Type - Worker Certification', value: 'NC'},
    {code: 'SOURCE_TYPE_WC', category: 'SOURCE_TYPE', description: 'Source Type - Worker Cancellation', value: 'NS'},
    {code: 'SOURCE_TYPE_RM', category: 'SOURCE_TYPE', description: 'Source Type - Reprint Medical Form', value: 'NS'},
    {code: 'SOURCE_TYPE_CD', category: 'SOURCE_TYPE', description: 'Source Type - Change Doctor', value: 'NS'},
    {code: 'SOURCE_TYPE_CG', category: 'SOURCE_TYPE', description: 'Source Type - Change Gender', value: 'NS'},
    {code: 'SOURCE_TYPE_WA', category: 'SOURCE_TYPE', description: 'Source Type - Worker Amendment', value: 'NS'},
    {code: 'SOURCE_TYPE_TE', category: 'SOURCE_TYPE', description: 'Source Type - Transaction Extent Expiry', value: 'NS'},
    {code: 'SOURCE_TYPE_REG_DOCTOR', category: 'SOURCE_TYPE', description: 'Source Type - Registration Doctor', value: 'NS'},
    {code: 'SOURCE_TYPE_REG_XRAYFACILITY', category: 'SOURCE_TYPE', description: 'Source Type - Registration Xray', value: 'NS'},
    {code: 'SOURCE_TYPE_REG_LABORATORY', category: 'SOURCE_TYPE', description: 'Source Type - Registration Laboratory', value: 'NS'},
    {code: 'SOURCE_TYPE_CHANGE_CLINIC_ADDRESS', category: 'SOURCE_TYPE', description: 'Source Type - Change Clinic Address', value: 'NS'},
    {code: 'SOURCE_TYPE_SFSREG', category: 'SOURCE_TYPE', description: 'Source Type - Special Renewal Rejected', value: 'NS'},

    {code: 'INSURANCE_PAYMENT_HOWDEN_PT', category: 'INSURANCE_PAYMENT', description: 'Insurance Payment GL Code - Howden - Portal', value: '322601307421'},
    {code: 'COMMISSION_PAYMENT_FGSB_PT', category: 'INSURANCE_PAYMENT', description: 'Insurance Commission Payment GL Code - FGSB - Portal', value: '322601307421'},

].each do |data|
    fs = FinanceSetting.where(:code => data[:code]).first_or_create
    fs.update(data)
end
puts("finance settings seeded")