[
    {code: '00', name:'Approved'},
    {code: '03', name:'Invalid Merchant'},
    {code: '05', name:'Invalid Seller Or Acquiring Bank Code'},
    {code: '09', name:'Transaction Pending'},
    {code: '12', name:'Invalid Transaction'},
    {code: '13', name:'Invalid Amount'},
    {code: '14', name:'Invalid Buyer Account'},
    {code: '20', name:'Invalid Response'},
    {code: '30', name:'Format Error'},
    {code: '31', name:'Invalid Bank'},
    {code: '39', name:'No Credit Account'},
    {code: '45', name:'Duplicate Seller Order Number'},
    {code: '46', name:'Invalid Seller Exchange Or Seller'},
    {code: '47', name:'Invalid Currency'},
    {code: '48', name:'Maximum Transaction Limit Exceeded'},
    {code: '49', name:'Merchant Specific Limit Exceeded'},
    {code: '50', name:'Invalid Seller for Merchant Specific Limit'},
    {code: '51', name:'Insufficient Funds'},
    {code: '53', name:'No Buyer Account Number'},
    {code: '57', name:'Transaction Not Permitted'},
    {code: '58', name:'Transaction To Merchant Not Permitted'},
    {code: '70', name:'Invalid Serial Number'},
    {code: '76', name:'Transaction Not Found'},
    {code: '77', name:'Invalid Buyer Name Or Buyer ID'},
    {code: '78', name:'Decryption Failed'},
    {code: '79', name:'Host Decline When Down'},
    {code: '80', name:'Buyer Cancel Transaction'},
    {code: '83', name:'Invalid Transaction Model'},
    {code: '84', name:'Invalid Transaction Type'},
    {code: '85', name:'Internal Error At Bank System'},
    {code: '87', name:'Debit Failed Exception Handling'},
    {code: '88', name:'Credit Failed Exception Handling'},
    {code: '89', name:'Transaction Not Received Exception Handling'},
    {code: '90', name:'Bank Internet Banking Unavailable'},
    {code: '92', name:'Invalid Buyer Bank'},
    {code: '96', name:'System Malfunction'},
    {code: '98', name:'MAC Error'},
    {code: '99', name:'Pending Authorization (Applicable for B2B model)'},
    {code: 'BB', name:'Blocked Bank'},
    {code: 'BC', name:'Transaction Cancelled By Customer'},
    {code: 'DA', name:'Invalid Application Type'},
    {code: 'DB', name:'Invalid Email Format'},
    {code: 'DC', name:'Invalid Maximum Frequency'},
    {code: 'DD', name:'Invalid Frequency Mode'},
    {code: 'DE', name:'Invalid Expiry Date'},
    {code: 'DF', name:'Invalid e-Mandate Buyer Bank ID'},
    {code: 'FE', name:'Internal Error'},
    {code: 'OE', name:'Transaction Rejected As Not In FPX Operating Hours'},
    {code: 'OF', name:'Transaction Timeout'},
    {code: 'SB', name:'Invalid  Acquiring Bank Code'},
    {code: 'XA', name:'Invalid Source IP Address (Applicable for B2B2 model)'},
    {code: 'XB', name:'Invalid Seller Exchange IP'},
    {code: 'XC', name:'Seller Exchange Encryption Error'},
    {code: 'XE', name:'Invalid Message'},
    {code: 'XF', name:'Invalid Number Of Orders'},
    {code: 'XI', name:'Invalid Seller Exchange'},
    {code: 'XM', name:'Invalid FPX Transaction Model'},
    {code: 'XN', name:'Transaction Rejected Due To Duplicate Seller Exchange Order Number'},
    {code: 'XO', name:'Duplicate Exchange Order Number'},
    {code: 'XS', name:'Seller Does Not Belong To Exchange'},
    {code: 'XT', name:'Invalid Transaction Type'},
    {code: 'XW', name:'Seller Exchange Date Difference Exceeded'},
    {code: '1A', name:'Buyer Session Timeout At Internet Banking Login Page'},
    {code: '1B', name:'Buyer Failed To Provide The Necessary Info To Login To Internet Banking Login Page'},
    {code: '1C', name:'Buyer Choose Cancel At Login Page'},
    {code: '1D', name:'Buyer Session Timeout At Account Selection Page'},
    {code: '1E', name:'Buyer Failed To Provide The Necessary Info At Account Selection Page'},
    {code: '1F', name:'Buyer Choose Cancel At Account Selection Page'},
    {code: '1G', name:'Buyer Session Timeout At TAC Request Page'},
    {code: '1H', name:'Buyer Failed To Provide The Necessary Info At TAC Request Page'},
    {code: '1I', name:'Buyer Choose Cancel At TAC Request Page'},
    {code: '1J', name:'Buyer Session Timeout At Confirmation Page'},
    {code: '1K', name:'Buyer Failed To Provide The Necessary Info At Confirmation Page'},
    {code: '1L', name:'Buyer Choose Cancel At Confirmation Page'},
    {code: '1M', name:'Internet Banking Session Timeout.'},
    {code: '2A', name:'Transaction Amount Is Lower Than Minimum Limit'},
    {code: '2X', name:'Transaction Is Canceled By Merchant'},
    {code: 'B0', name:'Order list format error'},
    {code: 'B1', name:'Invalid seller ID'},
    {code: 'B2', name:'Seller is not allow to refund'},
    {code: 'B3', name:'Seller is not allow to do multiple refund'},
    {code: 'B4', name:'Requested refund amount exceed maximum allowable'},
    {code: 'B5', name:'Original transcation ID is not found'},
    {code: 'B6', name:'Original transcation ID status is still pending debit/credit'},
    {code: 'B7', name:'Original transcation ID status was not successful'},
    {code: 'B8', name:'Previous refund request still pending debit/credit'},
    {code: 'B9', name:'Requested refund amount below minimun allowable'},
    {code: 'C1', name:'Invalid refund transcation model'},
    {code: 'C2', name:'Invalid refund buyer bank'},
    {code: 'C3', name:'Invalid refund seller bank'},
    {code: 'C4', name:'Refund request fail due to no valid order list'},
    {code: 'C5', name:'Order list contain duplicate seller order number'},
    {code: '1S', name:'Bulk Refund Successful Submited'},
    {code: 'OO', name:'Bulk Refund Debit Approved'}
].each do |data|
    fs = FpxResponseCode.where(:code => data[:code]).first_or_create
    fs.update(data)
end 
puts("fpx response codes seeded")