[
    {code: 'ABB0234', name: 'Affin Bank Berhad B2C - Test ID', display_name: 'Affin B2C - Test ID', msg_token: '01', status: 'ACTIVE'},
    {code: 'ABB0233', name: 'Affin Bank Berhad', display_name: 'Affin Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'ABMB0212', name: 'Alliance Bank Malaysia Berhad', display_name: 'Alliance Bank (Personal)', msg_token: '01', status: 'ACTIVE'},
    {code: 'AGRO01', name: 'BANK PERTANIAN MALAYSIA BERHAD (AGROBANK)', display_name: 'AGRONet', msg_token: '01', status: 'ACTIVE'},
    {code: 'AMBB0209', name: 'AmBank Malaysia Berhad', display_name: 'AmBank', msg_token: '01', status: 'ACTIVE'},
    {code: 'BIMB0340', name: 'Bank Islam Malaysia Berhad', display_name: 'Bank Islam', msg_token: '01', status: 'ACTIVE'},
    {code: 'BMMB0341', name: 'Bank Muamalat Malaysia Berhad', display_name: 'Bank Muamalat', msg_token: '01', status: 'ACTIVE'},
    {code: 'BKRM0602', name: 'Bank Kerjasama Rakyat Malaysia Berhad', display_name: 'Bank Rakyat', msg_token: '01', status: 'ACTIVE'},
    {code: 'BSN0601', name: 'Bank Simpanan Nasional', display_name: 'BSN', msg_token: '01', status: 'ACTIVE'},
    {code: 'BCBB0235', name: 'CIMB Bank Berhad', display_name: 'CIMB Clicks', msg_token: '01', status: 'ACTIVE'},
    {code: 'CIT0219', name: 'CITI Bank Berhad', display_name: 'Citibank', msg_token: '01', status: 'ACTIVE'},
    {code: 'HLB0224', name: 'Hong Leong Bank Berhad', display_name: 'Hong Leong Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'HSBC0223', name: 'HSBC Bank Malaysia Berhad', display_name: 'HSBC Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'KFH0346', name: 'Kuwait Finance House (Malaysia) Berhad', display_name: 'KFH', msg_token: '01', status: 'ACTIVE'},
    {code: 'MBB0228', name: 'Malayan Banking Berhad (M2E)', display_name: 'Maybank2E', msg_token: '01', status: 'ACTIVE'},
    {code: 'MB2U0227', name: 'Malayan Banking Berhad (M2U)', display_name: 'Maybank2U', msg_token: '01', status: 'ACTIVE'},
    {code: 'OCBC0229', name: 'OCBC Bank Malaysia Berhad', display_name: 'OCBC Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'PBB0233', name: 'Public Bank Berhad', display_name: 'Public Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'RHB0218', name: 'RHB Bank Berhad', display_name: 'RHB Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'TEST0021', name: 'SBI Bank A', display_name: 'SBI Bank A', msg_token: '01', status: 'ACTIVE'},
    {code: 'TEST0022', name: 'SBI Bank B', display_name: 'SBI Bank B', msg_token: '01', status: 'ACTIVE'},
    {code: 'TEST0023', name: 'SBI Bank C', display_name: 'SBI Bank C', msg_token: '01', status: 'ACTIVE'},
    {code: 'SCB0216', name: 'Standard Chartered Bank', display_name: 'Standard Chartered', msg_token: '01', status: 'ACTIVE'},
    {code: 'UOB0226', name: 'United Overseas Bank', display_name: 'UOB Bank', msg_token: '01', status: 'ACTIVE'},
    {code: 'UOB0229', name: 'United Overseas Bank - B2C Test', display_name: 'UOB Bank - Test ID', msg_token: '01', status: 'ACTIVE'},

    {code: 'ABB0232', name: 'Affin Bank Berhad', display_name: 'Affin Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'ABB0235', name: 'Affin Bank Berhad B2B', display_name: 'AFFINMAX', msg_token: '02', status: 'ACTIVE'},
    {code: 'ABMB0213', name: 'Alliance Bank Malaysia Berhad', display_name: 'Alliance Bank (Business)', msg_token: '02', status: 'ACTIVE'},
    {code: 'AGRO02', name: 'BANK PERTANIAN MALAYSIA BERHAD (AGROBANK)', display_name: 'AGRONetBIZ', msg_token: '02', status: 'ACTIVE'},
    {code: 'AMBB0208', name: 'AmBank Malaysia Berhad', display_name: 'AmBank', msg_token: '02', status: 'ACTIVE'},
    {code: 'BIMB0340', name: 'Bank Islam Malaysia Berhad', display_name: 'Bank Islam', msg_token: '02', status: 'ACTIVE'},
    {code: 'BMMB0342', name: 'Bank Muamalat Malaysia Berhad', display_name: 'Bank Muamalat', msg_token: '02', status: 'ACTIVE'},
    {code: 'BNP003', name: 'BNP Paribas Malaysia Berhad', display_name: 'BNP Paribas', msg_token: '02', status: 'ACTIVE'},
    {code: 'BCBB0235', name: 'CIMB Bank Berhad', display_name: 'CIMB Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'CIT0218', name: 'CITI Bank Berhad', display_name: 'Citibank Corporate Banking', msg_token: '02', status: 'ACTIVE'},
    {code: 'DBB0199', name: 'Deutsche Bank Berhad', display_name: 'Deutsche Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'HLB0224', name: 'Hong Leong Bank Berhad', display_name: 'Hong Leong Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'HSBC0223', name: 'HSBC Bank Malaysia Berhad', display_name: 'HSBC Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'BKRM0602', name: 'Bank Kerjasama Rakyat Malaysia Berhad', display_name: 'i-bizRAKYAT', msg_token: '02', status: 'ACTIVE'},
    {code: 'KFH0346', name: 'Kuwait Finance House (Malaysia) Berhad', display_name: 'KFH', msg_token: '02', status: 'ACTIVE'},
    {code: 'MBB0228', name: 'Malayan Banking Berhad (M2E)', display_name: 'Maybank2E', msg_token: '02', status: 'ACTIVE'},
    {code: 'OCBC0229', name: 'OCBC Bank Malaysia Berhad', display_name: 'OCBC Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'PBB0233', name: 'Public Bank Berhad', display_name: 'Public Bank PBe', msg_token: '02', status: 'ACTIVE'},
    {code: 'PBB0234', name: 'Public Bank Enterprise', display_name: 'Public Bank PB enterprise', msg_token: '02', status: 'ACTIVE'},
    {code: 'RHB0218', name: 'RHB Bank Berhad', display_name: 'RHB Bank', msg_token: '02', status: 'ACTIVE'},
    {code: 'TEST0021', name: 'SBI Bank A', display_name: 'SBI Bank A', msg_token: '02', status: 'ACTIVE'},
    {code: 'TEST0022', name: 'SBI Bank B', display_name: 'SBI Bank B', msg_token: '02', status: 'ACTIVE'},
    {code: 'TEST0023', name: 'SBI Bank C', display_name: 'SBI Bank C', msg_token: '02', status: 'ACTIVE'},
    {code: 'SCB0215', name: 'Standard Chartered Bank', display_name: 'Standard Chartered', msg_token: '02', status: 'ACTIVE'},
    {code: 'UOB0228', name: 'United Overseas Bank B2B Regional', display_name: 'UOB Regional', msg_token: '02', status: 'ACTIVE'}
].each do |data|
    fs = FpxBank.where(:code => data[:code], :msg_token => data[:msg_token]).first_or_create
    fs.update(data)
end 
puts("fpx banks seeded")