# Please refer to https://docs.google.com/spreadsheets/d/1vYmaEycDI_7Q6y_6X8iW_xHjjaqNKVntVwInTQEJYkU/edit#gid=0 for mapping.

quarantine_reasons = [
    { code: "10000", reason: "Certified SUITABLE but was previously UNSUITABLE (last transaction)" },
    { code: "10001", reason: "Abnormal lab/x-ray findings with incomplete (no certification) last transaction." },
    { code: "10002", reason: "Certified SUITABLE with a blood group that is different from previous transactions." },
    { code: "10003", reason: "Worker has been manually tagged for monitoring" },
    { code: "10004", reason: "Worker certified UNSUITABLE with normal physical, laboratory and Xray findings" },
    { code: "10005", reason: "Certified SUITABLE with lab OR/AND x-ray tests not done." },
    { code: "10006", reason: "Re-use Passport detected with previously certified UNSUITABLE" },
    { code: "10007", reason: "Certified UNSUITABLE with previously UNSUITABLE (last transaction)" },
    { code: "10008", reason: "In-House PCR does not agree with the Digital X-Ray finding." }, # Please note that 10008 and 10013 are very similar but used differently. 10008 is used by XQCC when Pcr results do not match xray exam results. 10013 is used when there is third concurrence, and medical pending review is inserted. Also, 10008 is used in XqccQuarantineReason, while 10013 is used in TransactionQuarantineReason.
    { code: "10009", reason: "Blood Group Discrepancy with Previous Transaction" },
    # { code: "10010", reason: "Certified SUITABLE with previously Medical UNSUITABLE (last transaction)"}, - Removed 2020-10-16 - NF-1752 - To combine with 10000
    { code: "10011", reason: "Certified SUITABLE with previously X-ray UNSUITABLE (last transaction)"},
    { code: "10012", reason: "Certified UNSUITABLE with previously X-ray UNSUITABLE (last transaction)"},
    { code: "10013", reason: "In-House PCR does not agree with the Digital X-Ray finding. Case transferred by XQCC Department." },
    { code: "1010", reason: "Worker certified SUITABLE with medical history (HIVS)" },
    { code: "1012", reason: "Worker certified SUITABLE with medical history (Tuberculosis)" },
    { code: "1013", reason: "Worker certified SUITABLE with medical history (Leprosy)" },
    { code: "1014", reason: "Worker certified SUITABLE with medical history (Viral Hepatitis B)" },
    { code: "1015", reason: "Worker certified SUITABLE with medical history (Psychiatric Illness)" },
    { code: "1016", reason: "Worker certified SUITABLE with medical history (Epilepsy)" },
    { code: "1017", reason: "Worker certified SUITABLE with medical history (Cancer)" },
    { code: "1018", reason: "Worker certified SUITABLE with medical history (STD)" },
    { code: "1019", reason: "Worker certified SUITABLE with positive Malaria (ELISA) and positive BFMP(Laboratory Results)" },
    { code: "1020", reason: "Worker certified SUITABLE with medical history (Malaria)" },
    { code: "1021", reason: "Worker certified SUITABLE with medical history (Hypertension)" },
    { code: "1022", reason: "Worker certified SUITABLE with medical history (Heart Diseases)" },
    { code: "1023", reason: "Worker certified SUITABLE with medical history (Asthma)" },
    { code: "1024", reason: "Worker certified SUITABLE with medical history (Diabetes Mellitus)" },
    { code: "1025", reason: "Worker certified SUITABLE with medical history (Peptic Ulcer)" },
    { code: "1026", reason: "Worker certified SUITABLE with medical history (Kidney Diseases)" },
    { code: "1027", reason: "Worker certified SUITABLE with medical history (Other)" },
    { code: "2040", reason: "Worker certified SUITABLE with diastolic blood pressure greather or equal to 100 mm. Hg" },
    { code: "2041", reason: "Worker certified SUITABLE with systolic blood pressure greater or equal to 180 mm. Hg." },
    { code: "2042", reason: "Worker certified SUITABLE with physical examination (diastolic blood pressure equal or more than 90 mmHg)" },
    { code: "2043", reason: "Worker certified SUITABLE with physical examination (systolic blood pressure equal or more than 140 mmHg)" },
    { code: "2050", reason: "Worker certified SUITABLE with physical examination (Chronic Skin Rash)" },
    { code: "2060", reason: "Worker certified SUITABLE with physical examination (Anesthetic Skin Patch)" },
    { code: "2070", reason: "Worker certified SUITABLE with physical examination (Deformities of Limbs)" },
    { code: "2080", reason: "Worker certified SUITABLE with physical examination (Pallor)" },
    { code: "2090", reason: "Worker certified SUITABLE with physical examination (Jaundice)" },
    { code: "2100", reason: "Worker certified SUITABLE with physical examination (Lymph Node Enlargment)" },
    { code: "2111", reason: "Worker certified SUITABLE with defective vision test unaided (left)" },
    { code: "2112", reason: "Worker certified SUITABLE with defective vision test unaided (right)" },
    { code: "2113", reason: "Worker certified SUITABLE with defective vision test aided (left)" },
    { code: "2114", reason: "Worker certified SUITABLE with defective vision test aided (right)" },
    { code: "2121", reason: "Worker certified SUITABLE with defective hearing (left)" },
    { code: "2122", reason: "Worker certified SUITABLE with defective hearing (right)" },
    { code: "2130", reason: "Worker certified SUITABLE with physical examination (Others)" },
    { code: "3101", reason: "Worker certified SUITABLE with cardiovascular system (heart size)" },
    { code: "3102", reason: "Worker certified SUITABLE with cardiovascular system (Heart Sounds)" },
    { code: "3103", reason: "Worker certified SUITABLE with cardiovascular system (Other findings)" },
    { code: "3201", reason: "Worker certified SUITABLE with respiratory system (Breath Sounds)" },
    { code: "3202", reason: "Worker certified SUITABLE with respiratory system (Other findings)" },
    { code: "3301", reason: "Worker certified SUITABLE with gastrointestinal system (Liver)" },
    { code: "3302", reason: "Worker certified SUITABLE with gastrointestinal system (Spleen)" },
    { code: "3303", reason: "Worker certified SUITABLE with gastrointestinal system (Swelling)" },
    { code: "3304", reason: "Worker certified SUITABLE with gastrointestinal system (Lymph Nodes)" },
    { code: "3305", reason: "Worker certified SUITABLE with gastrointestinal system (Rectal Examination)" },
    { code: "3306", reason: "Worker certified SUITABLE with gastrointestinal system (Other findings)" },
    { code: "3401", reason: "Worker certified SUITABLE with nervous system and mental status (General Mental status)" },
    { code: "3402", reason: "Worker certified SUITABLE with nervous system and mental status (Speech)" },
    { code: "3403", reason: "Worker certified SUITABLE with nervous system and mental status (Cognitive function)" },
    { code: "3404", reason: "Worker certified SUITABLE with nervous system and mental status (Size of Peripheral Nerves)" },
    { code: "3405", reason: "Worker certified SUITABLE with nervous system and mental status (Motor Power)" },
    { code: "3406", reason: "Worker certified SUITABLE with nervous system and mental status (Sensory)" },
    { code: "3407", reason: "Worker certified SUITABLE with nervous system and mental status (Reflexes)" },
    { code: "3408", reason: "Worker certified SUITABLE with nervous system and mental status (Others)" },
    { code: "3501", reason: "Worker certified SUITABLE with genitourinary system (Kidney)" },
    { code: "3502", reason: "Worker certified SUITABLE with genitourinary system (Discharge)" },
    { code: "3503", reason: "Worker certified SUITABLE with genitourinary system (Sores Ulcers)" },
    { code: "3525", reason: "Worker certified SUITABLE with abnormal discharge (Breast Examination)" },
    { code: "3526", reason: "Worker certified SUITABLE with abnormal lump (Breast Examination)" },
    { code: "3527", reason: "Worker certified SUITABLE with abnormal axillary lymph node (Breast Examination) " },
    { code: "3528", reason: "Worker certified SUITABLE with abnormal Others (Breast Examination)" },
    { code: "4000", reason: "Worker certified SUITABLE with lab not done" },
    { code: "4110", reason: "Worker certified SUITABLE with abnormal urine test where his/her urine contains sugar (Laboratory Results)" },
    { code: "4120", reason: "Worker certified SUITABLE with abnormal urine test where his/her urine contains albumin (Laboratory Results)" },
    { code: "4130", reason: "Worker certified SUITABLE with abnormal microscopic examination(Labratory Results)" },
    { code: "4140", reason: "Worker certified SUITABLE with abnormal specific gravity (Laboratory Results)" },
    { code: "5000", reason: "Worker certified SUITABLE with xray not done" },
    { code: "5010", reason: "Worker certified SUITABLE with abnormal Thoracic cage (X-ray findings)" },
    { code: "5020", reason: "Worker certified SUITABLE with abnormal Heart Shape and Size (X-ray findings)" },
    { code: "5030", reason: "Worker certified SUITABLE with abnormal Lung Fields (X-ray findings)" }, # Note: 7090 - Worker certified SUITABLE but there is inconsistency between Part IV, Section B: X-Ray Findings (Active/focal lesion-tuberculosis or cancer) and Part V, Doctors Findings (Tuberculosis). Has been merged with 5030.
    { code: "5040", reason: "Worker certified SUITABLE with abnormal Focal Lesion" }, # Note: 7090 - Worker certified SUITABLE but there is inconsistency between Part IV, Section B: X-Ray Findings (Active/focal lesion-tuberculosis or cancer) and Part V, Doctors Findings (Tuberculosis). Has been merged with 5040.
    { code: "5050", reason: "Worker certified SUITABLE with Other abnormalities (Any Other Findings)" },
    { code: "5060", reason: "Worker certified SUITABLE with abnormal Mediastinum and Hila (X-ray findings)" }, # Note: 5041 - There is inconsistency between Part IV: Section B - X-Ray Findings (Abnormal Mediastinum and Hila) and Part V - Doctor Findings (Tuberculosis). Has been merged with 5060.
    { code: "5070", reason: "Worker certified SUITABLE with abnormal Pleura / Hemidiaphragms / Costopherenic Angles (X-ray findings)" }, # Note 5042 - There is inconsistency between Part IV: Section B - X-Ray Findings (Abnormal Pleura/Hemidiaphragms/Costopheric Angles) and Part V - Doctor Findings (Tuberculosis)
    { code: "6010", reason: "Worker certified SUITABLE with HIV (Certification condition)" },
    { code: "6011", reason: "Worker certified SUITABLE with positive HIV (Laboratory Results)" },
    { code: "6012", reason: "Worker certified SUITABLE with positive HBsAg (Laboratory Results)" },
    { code: "6020", reason: "Worker certified SUITABLE with Tuberculosis (Certification condition)" },
    { code: "6030", reason: "Worker certified SUITABLE with Malaria (Certification condition)" },
    { code: "6040", reason: "Worker certified SUITABLE with Leprosy (Certification condition)" },
    { code: "6050", reason: "Worker certified SUITABLE with STD (Certification condition)" },
    { code: "6060", reason: "Worker certified SUITABLE with Hepatitis B (Certification condition)" },
    { code: "6070", reason: "Worker certified SUITABLE with Cancer (Certification condition)" },
    { code: "6080", reason: "Worker certified SUITABLE with Epilepsy (Certification condition)" },
    { code: "6090", reason: "Worker certified SUITABLE with Psychiatric Illness (Certification condition)" },
    { code: "6100", reason: "Worker certified SUITABLE with Unsuitable condition Others (Certification condition)" }, # Note: 7240 - Worker certified SUITABLE with Unsuitable Condition Others (Others). has been merged with 6100.
    { code: "6110", reason: "Worker certified SUITABLE with pregnancy (Certification condition)" },
    { code: "6120", reason: "Worker certified SUITABLE with positive Opiates (Laboratory Results)" },
    { code: "6130", reason: "Worker certified SUITABLE with positive Cannabis (Laboratory Results)" },
    { code: "7020", reason: "Worker certified SUITABLE but there is inconsistency between Part IV Section A: Laboratory Results (HIV) and Part V Doctor Certification." },
    { code: "7030", reason: "Worker certified SUITABLE but there is inconsistency between Part IV Section A: Laboratory Result (HBsAg) and Part V Doctor Certification." },
    { code: "7040", reason: "Worker certified UNSUITABLE with positive VDRL and negative TPHA" },
    { code: "7041", reason: "Worker certified SUITABLE but there is inconsistency between Part IV, Section A:Labotarory Results (VDRL) and Part V, Doctors Findings (Sexually Transmitted Diseases). TPHA is not specified as lab submitted via IBTv2." },
    { code: "7050", reason: "Worker certified SUITABLE but there is inconsistency between Part IV Section A: Laboratory Result (Malaria and BFMP) and Part V Doctor Certification." },
    { code: "7060", reason: "Worker certified SUITABLE with Urine contain opiates (Certification condition)" },
    { code: "7070", reason: "Worker certified SUITABLE with Urine contain Cannabis (Certification condition)" },
    { code: "7080", reason: "Worker certified SUITABLE with positive UPT and positive serum BHCG (Laboratory Results)" },
    { code: "7090", reason: "Worker certified SUITABLE but there is inconsistency between Part IV, Section B: X-Ray Findings (Active/focal lesion-tuberculosis or cancer) and Part V, Doctors Findings (Tuberculosis)" },
    { code: "7100", reason: "Worker certified SUITABLE with positive VDRL and positive TPHA (Laboratory Results)" },
    { code: "7110", reason: "Worker certified SUITABLE with nervous system and mental status (Speech Quality)" },
    { code: "7130", reason: "Worker certified SUITABLE with abnormal cognitive function (Nervous system and mental status)" },
    { code: "7150", reason: "Worker certified UNSUITABLE with positive Malaria and negative BFMP" },
    { code: "7160", reason: "Worker certified SUITABLE with Part IV, Section A:Laboratory Results (Pregnancy Test and Serum Beta-HCG)" },
    { code: "7170", reason: "Worker certified UNSUITABLE with positive UPT and negative serum BHCG (Laboratory Results)" },
    { code: "7180", reason: "Worker certified SUITABLE with Hypertension (Certification condition)" },
    { code: "7190", reason: "Worker certified SUITABLE with Heart Diseases (Certification condition)" },
    { code: "7200", reason: "Worker certified SUITABLE with Bronchial Asthma (Certification condition)" },
    { code: "7210", reason: "Worker certified SUITABLE with Diabetes Mellitus (Certification condition)" },
    { code: "7220", reason: "Worker certified SUITABLE with Peptic Ulcer (Certification condition)" },
    { code: "7230", reason: "Worker certified SUITABLE with Kidney Disease (Certification condition)" },
    { code: "8010", reason: "Worker certified UNSUITABLE without any of the condition in Part IV #1 - #13 turned on (YES) but with reasonable reason" },
    { code: "9010", reason: "Fail to notify Medical Officer Of Health of occurrence of HIV/AIDS Disease" },
    { code: "9020", reason: "Fail to notify Medical Officer Of Health of occurrence of Tuberculosis Disease" },
    { code: "9030", reason: "Fail to notify Medical Officer Of Health of occurrence of Malaria Disease" },
    { code: "9040", reason: "Fail to notify Medical Officer Of Health of occurrence of Leprosy Disease" },
    { code: "9050", reason: "Fail to notify Medical Officer Of Health of occurrence of Sexually Transmitted Disease" },
    { code: "9060", reason: "Fail to notify Medical Officer Of Health of occurrence of Hepetitis Disease" }
]

quarantine_reasons.each do |hash|
    qr = QuarantineReason.find_or_initialize_by(code: hash[:code])
    qr.update(reason: hash[:reason])
end

puts("Quarantine Reasons seeded")