# system configurations

[
    {category: "SYSTEM", code: "COMPANY_NAME", name: "Company name", value: "FOMEMA SDN. BHD."},
    {category: "SYSTEM", code: "COMPANY_NAME_INVOICE", name: "Company name (Invoice)", value: "FOMEMA Global Sdn Bhd"},
    {category: "SYSTEM", code: "COMPANY_ADDR", name: "Company address", value: "No 1, Jalan Fomema"},
    {category: "SYSTEM", code: "COMPANY_PHONE", name: "Company phone number", value: "+60300000001"},
    {category: "SYSTEM", code: "COMPANY_FAX", name: "Company fax number", value: "+60300000002"},
    {category: "SYSTEM", code: "COMPANY_REGNO", name: "Company registration number", value: "199401026610 (312291-X)"},
    {category: "SYSTEM", code: "COMPANY_REGNO_GLOBAL", name: "Company registration number (global)", value: "199601032301 (404653-V)"},
    {category: "SYSTEM", code: "EMPLOYER_APPROVAL", name: "Employer registration require approval", value: "0"},
    {category: "SYSTEM", code: "AGENCY_APPROVAL", name: "Agency registration require approval", value: "0"},
    {category: "SYSTEM", code: "EMPLOYER_BULKCOMMENT", name: "Employer bulk registration require comment", value: "1"},
    {category: "SYSTEM", code: "PASSWORDPOLICY_APPROVAL", name: "Password policy require approval", value: "0"},
    {category: "SYSTEM", code: "BULLETIN_RECENT", name: "Number of recent bulletin", value: "5"},
    {category: "SYSTEM", code: "EMPLOYER_REGISTER_APPROVAL_REPLY_DAYS", name: "Number of working days to perform approval and send email notification (Employer)", value: "2"},
    {category: "SYSTEM", code: "AGENCY_REGISTER_APPROVAL_REPLY_DAYS", name: "Number of working days to perform approval and send email notification (Agency)", value: "2"},
    {category: "SYSTEM", code: "JIM_BIODATA_TIMEOUT", name: "JIM Biodata Timeout", value: "30"},
    {category: "XQCC", code: "XQCC_PICKUPMETHOD", name: "XQCC pickup method", value: "FACILITY"}, # FIFO/FACILITY
    {category: "XQCC", code: "XQCC_FIFO_BUNDLEASSIGN", name: "XQCC pickup count (FIFO)", value: "5"},
    {category: "XQCC", code: "XQCC_IQA", name: "XQCC IQA pickup denominator (1/n)", value: "5"},
    {category: "XQCC", code: "XQCC_MAID_BUNDLEASSIGN", name: "XQCC pickup count (Maid Online)", value: "2"},
    {category: "SYSTEM", code: "WORKER_AMENDREQDOC", name: "Foreign worker amendment require document", value: "1"},
    {category: "SYSTEM", code: "PORTAL_WORKER_AMENDMENT_FOC", name: "Foreign worker amendment (Portal) is FOC", value: "0"},
    {category: "FINANCE", code: "DOCTOR_DEFAULT_MALE_RATE", name: "Doctor Default Male Rate", value: "60"},
    {category: "FINANCE", code: "DOCTOR_DEFAULT_FEMALE_RATE", name: "Doctor Default Female Rate", value: "60"},
    {category: "FINANCE", code: "LABORATORY_DEFAULT_MALE_RATE", name: "Laboratory Default Male Rate", value: "48"},
    {category: "FINANCE", code: "LABORATORY_DEFAULT_FEMALE_RATE", name: "Laboratory Default Female Rate", value: "48"},
    {category: "FINANCE", code: "XRAY_FACILITY_DEFAULT_MALE_RATE", name: "X-Ray Facility Default Male Rate", value: "22.50"},
    {category: "FINANCE", code: "XRAY_FACILITY_DEFAULT_FEMALE_RATE", name: "X-Ray Facility Default Female Rate", value: "22.50"},
    {category: "FINANCE", code: "DOCTOR_SERVICE_PROVIDER_GROUP_DEFAULT_MALE_RATE", name: "Doctor Service Provider Group Default Male Rate", value: "60"},
    {category: "FINANCE", code: "DOCTOR_SERVICE_PROVIDER_GROUP_DEFAULT_FEMALE_RATE", name: "Doctor Service Provider Group Default Female Rate", value: "60"},
    {category: "FINANCE", code: "LABORATORY_SERVICE_PROVIDER_GROUP_DEFAULT_MALE_RATE", name: "Laboratory Service Provider Group Default Male Rate", value: "48"},
    {category: "FINANCE", code: "LABORATORY_SERVICE_PROVIDER_GROUP_DEFAULT_FEMALE_RATE", name: "Laboratory Service Provider Group Default Female Rate", value: "48"},
    {category: "FINANCE", code: "XRAY_FACILITY_SERVICE_PROVIDER_GROUP_DEFAULT_MALE_RATE", name: "X-Ray Facility Service Provider Group Default Male Rate", value: "22.50"},
    {category: "FINANCE", code: "XRAY_FACILITY_SERVICE_PROVIDER_GROUP_DEFAULT_FEMALE_RATE", name: "X-Ray Facility Service Provider Group Default Female Rate", value: "22.50"},
    {category: "SYSTEM", code: "TRANSACTION_EXPIRY_DAYS", name: "Transaction expiry days", value: "30"},
    {category: "SYSTEM", code: "REPRINTPLY", name: "Reprint medical form require payment<br><small><i>(applicable for portal only)</i></small>", value: "0"},
    {category: "SYSTEM", code: "RADIOLOGIST_AUTORELEASE_NORMAL", name: "Auto-Release On Radiologist (NORMAL)", value: "0"},
    {category: "SYSTEM", code: "RADIOLOGIST_AUTORELEASE_ABNORMAL", name: "Auto-Release On Radiologist (ABNORMAL)", value: "0"},
    {category: "SYSTEM", code: "XRAY_WS_TOKEN_EXPIRY", name: "X-Ray Web Service Token Expiry (Minute)", value: "10"},
    {category: "SYSTEM", code: "PATI_NIOS", name: "PATI (NIOS)", value: "0"},
    {category: "SYSTEM", code: "PATI_PORTAL", name: "PATI (PORTAL)", value: "0"},
    {category: "SYSTEM", code: "REMARK_INVOICE", name: "Remark under company name in invoice", value: "Appointed collection agent for FOMEMA Sdn. Bhd."},
    {category: "SYSTEM", code: "LAST_X_DAYS_TO_UPDATE_TRANSACTION", name: "Last X days to update transaction and IMM", value: "0"},
    {category: "FINANCE", code: "INSURANCE_COMMISSION", name: "Insurance Commission (%)", value: "0"},
    {category: "FINANCE", code: "INSURANCE_RECOGNIZED_COLLECTION", name: "Recognized Insurance Upon Collection", value: "1"},
    {category: "FINANCE", code: "HOWDEN_CODE", name: "Howden Vendor Code", value: "INSHOWDEN"},
    {category: "FINANCE", code: "FGSB_CODE", name: "Fomema Global Vendor Code", value: "INSFOMGLO"},
    {category: "FINANCE", code: "TFSB_CODE", name: "TrekFomema Vendor Code", value: "INSFOMGLO"},
    {category: "SYSTEM", code: "BLOCK_EMAIL_WITH_PLUS_SIGN", name: "Block email with plus sign", value: "0"},
    {category: "SYSTEM", code: "INSURANCE_SHARE_DATA_CONFIRMATION", name: "Insurance Share Data Confirmation", value: "1"},
    {category: "SYSTEM", code: "INSURANCE_EXPIRY_GRACE", name: "Insurance allow purchase X days before expiry", value: "90"},
    {category: "SYSTEM", code: "BLOCK_TRANSACTION_RENEWAL_WITHIN_DAYS", name: "Block Transaction Renewal Within Days", value: "30"},
    {category: "SYSTEM", code: "AGENCY_EXPIRY_DAYS", name: "Agency Expiry Days", value: "365"},
    {category: "SYSTEM", code: "AGENCY_RENEWAL_X_DAYS_BEFORE_EXPIRY", name: "Agency Renewal X Days Before Expiry", value: "30"},
    {category: "SYSTEM", code: "SEND_UNSUITABLE_EMAIL_AFTER_X_DAYS_WITHOUT_APPEAL", name: "Send Unsuitable Email After X Days Without Appeal", value: "14"},
    {category: "SYSTEM", code: "JIM_ENABLE_GET_BIODATA", name: "Enable JIM Get Biodata", value: "1"},
    {category: "SYSTEM", code: "MERTS_TRANSMISSION_EXPIRY_DAYS", name: "MERTS transmission expiry days<br><small><i>(from examination date)</i></small>", value: "30"},
    {category: "SYSTEM", code: "STAT_PENDING_ORDER_MONTHS", name: "Statistic for pending order months", value: "30"},
    {category: "SYSTEM", code: "INIT_APPEAL_IN_DAYS", name: "Initiate Appeal within Days", value: "90"},
    {category: "SYSTEM", code: "XRAY_NEW_FLOW_START_DATE", name: "X-ray new flow start date", value: "2022-04-02 00:00:00"},
    {category: "SYSTEM", code: "FINANCE_EMAIL", name: "Finance Email", value: "financegroup@fomema.com.my"},
    {category: "SYSTEM", code: "REFUND_PAYMENT_FAILED_REMINDER_DAYS", name: "Send Refund Payment Failed Reminder After X Days Updated", value: "2"},
    {category: "SYSTEM", code: "MSPD_EMAIL", name: "Mspd Email", value: "mspd@fomema.com.my"},
    {category: "SYSTEM", code: "MSPD_INACTIVE_GROUP_IN_X_DAYS", name: "MSPD inactive group email", value: "30"},
    {category: "SYSTEM", code: "MEDICAL_PR_IQA", name: "Medical Pending Review IQA", value: "1"},
    {category: "SYSTEM", code: "CONDITIONAL_SUCCESS_REMINDER_DAYS", name: "Conditional success appeal reminder email", value: "365"},
    {category: "SYSTEM", code: "FIOT_EMAIL", name: "FIOT Email", value: "fiotgroup@fiot.my"},
    {category: "SYSTEM", code: "MAX_ORDER_ITEM_COUNT", name: "Maximum Order Item Count", value: "0"},
].each do |data|
    sc = SystemConfiguration.where(code: data[:code]).first_or_create do |sc|
        sc.update({
            name: data[:name],
            value: data[:value],
            category: data[:category]
        })
    end
end

puts "system configurations seeded"