# zones
[
    ['AK', 'AIR KEROH'],
    ['AT', 'AIR TAWAR'],
    ['AG', 'ALOR GAJAH'],
    ['AS', 'ALOR STAR'],
    ['BB', 'BATU BERENDAM'],
    ['BJ', 'BATU GAJAH'],
    ['OB', 'BCB OTHER BRANCHES'],
    ['BG', 'BENTONG'],
    ['BR', 'BIDOR'],
    ['BN', 'BRINCHANG'],
    ['BU', 'BUKIT BARU'],
    ['BW', 'BUTTER WORTH'],
    ['CH', 'CAMERON HIGHLANDS'],
    ['FH', 'FRASER HILL'],
    ['GH', 'GENTING HIGHLANDS'],
    ['GG', 'GOPENG'],
    ['HC', 'HOUSE CHEQUE'],
    ['IP', 'IPOH'],
    ['JN', 'JASIN'],
    ['JA', 'JENGKA'],
    ['JT', 'JERANTUT'],
    ['JR', 'JOHOR'],
    ['JB', 'JOHOR BHARU'],
    ['KR', 'KAMPAR'],
    ['KA', 'KANGAR'],
    ['KK', 'KARAK'],
    ['KH', 'KEDAH'],
    ['LN', 'KELANTAN'],
    ['KE', 'KENINGGAU'],
    ['KG', 'KLEBANG'],
    ['KB', 'KOTA BHARU'],
    ['KU', 'KOTA KINABALU'],
    ['KS', 'KUALA LIPIS'],
    ['KL', 'KUALA LUMPUR'],
    ['KT', 'KUALA TERENGGANU'],
    ['KN', 'KUANTAN'],
    ['LD', 'LAHAD DATU'],
    ['LP', 'LANGKAP'],
    ['LW', 'LANGKAWI'],
    ['LI', 'LIMBANG'],
    ['LT', 'LUMUT'],
    ['MN', 'MARAN'],
    ['MD', 'MASJID TANAH'],
    ['MA', 'MELAKA'],
    ['MT', 'MELAKA TOWN'],
    ['MB', 'MENTAKAB'],
    ['MU', 'MERLIMAU'],
    ['NS', 'NEGERI SEMBILAN'],
    ['PA', 'PAHANG'],
    ['PK', 'PANGKOR'],
    ['PE', 'PERAK'],
    ['PS', 'PERLIS'],
    ['MO', 'POSTAL MONEY ORDER'],
    ['PI', 'PRAI'],
    ['PG', 'PULAU PINANG'],
    ['RB', 'RAUB'],
    ['SA', 'SABAH'],
    ['SK', 'SANDAKAN'],
    ['SW', 'SARAWAK'],
    ['SE', 'SELANGOR'],
    ['ST', 'SIMPANG EMPAT'],
    ['SN', 'SITIAWAN'],
    ['SR', 'SLIM RIVER'],
    ['SU', 'SUNGAI UDANG'],
    ['SI', 'SUNGKAI'],
    ['TN', 'TAMPIN'],
    ['TM', 'TANJUNG MALIM'],
    ['TH', 'TAPAH'],
    ['TU', 'TAWAU'],
    ['TI', 'TELUK INTAN'],
    ['TE', 'TEMERLOH'],
    ['TR', 'TERENGGANU'],
    ['TG', 'TRIANG'],
    ['PO', 'WANG POS'],
    ['WP', 'WILAYAH PERSEKUTUAN']
].each do |row|
    Zone.create!({
        code: row[0],
        name: row[1]
    })
end
puts("zones seeded")