language: ruby
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
rvm:
  - 2.2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
script:
  - bundle exec rspec
