---
:concurrency: 5

:queues:
  - ['default', 2]
  - ['mailers', 2]
development:
  :concurrency: 5
staging:
  :concurrency: 10
  :pidfile: /tmp/pids/sidekiq-0.pid
production:
  :concurrency: 20
  :pidfile: /tmp/pids/sidekiq-0.pid
