class RemoveMertsExaminationColumns < ActiveRecord::Migration[6.0]
    def change
        remove_column :doctor_examinations, :history_hiv
        remove_column :doctor_examinations, :history_hiv_date
        remove_column :doctor_examinations, :history_tuberculosis
        remove_column :doctor_examinations, :history_tuberculosis_date
        remove_column :doctor_examinations, :history_leprosy
        remove_column :doctor_examinations, :history_leprosy_date
        remove_column :doctor_examinations, :history_viral_hepatitis
        remove_column :doctor_examinations, :history_viral_hepatitis_date
        remove_column :doctor_examinations, :history_psychiatric_illness
        remove_column :doctor_examinations, :history_psychiatric_illness_date
        remove_column :doctor_examinations, :history_epilepsy
        remove_column :doctor_examinations, :history_epilepsy_date
        remove_column :doctor_examinations, :history_cancer
        remove_column :doctor_examinations, :history_cancer_date
        remove_column :doctor_examinations, :history_std
        remove_column :doctor_examinations, :history_std_date
        remove_column :doctor_examinations, :history_malaria
        remove_column :doctor_examinations, :history_malaria_date
        remove_column :doctor_examinations, :history_hypertension
        remove_column :doctor_examinations, :history_hypertension_date
        remove_column :doctor_examinations, :history_heart_diseases
        remove_column :doctor_examinations, :history_heart_diseases_date
        remove_column :doctor_examinations, :history_bronchial_asthma
        remove_column :doctor_examinations, :history_bronchial_asthma_date
        remove_column :doctor_examinations, :history_diabetes_mellitus
        remove_column :doctor_examinations, :history_diabetes_mellitus_date
        remove_column :doctor_examinations, :history_peptic_ulcer
        remove_column :doctor_examinations, :history_peptic_ulcer_date
        remove_column :doctor_examinations, :history_kidney_diseases
        remove_column :doctor_examinations, :history_kidney_diseases_date
        remove_column :doctor_examinations, :history_other
        remove_column :doctor_examinations, :history_other_date
        remove_column :doctor_examinations, :history_taken_drug_recently
        remove_column :doctor_examinations, :history_comment
        remove_column :doctor_examinations, :physical_chronic_skin_rash
        remove_column :doctor_examinations, :physical_anaesthetic_skin_patch
        remove_column :doctor_examinations, :physical_deformities_of_limbs
        remove_column :doctor_examinations, :physical_pallor
        remove_column :doctor_examinations, :physical_jaundice
        remove_column :doctor_examinations, :physical_lymph_node_enlargement
        remove_column :doctor_examinations, :physical_vision_test_unaided_left
        remove_column :doctor_examinations, :physical_vision_test_unaided_right
        remove_column :doctor_examinations, :physical_vision_test_aided_left
        remove_column :doctor_examinations, :physical_vision_test_aided_right
        remove_column :doctor_examinations, :physical_hearing_ability_left
        remove_column :doctor_examinations, :physical_hearing_ability_right
        remove_column :doctor_examinations, :physical_other
        remove_column :doctor_examinations, :physical_comment
        remove_column :doctor_examinations, :system_cardiovascular_heart_size
        remove_column :doctor_examinations, :system_cardiovascular_heart_sounds
        remove_column :doctor_examinations, :system_cardiovascular_other_findings
        remove_column :doctor_examinations, :system_respiratory_breath_sounds
        remove_column :doctor_examinations, :system_respiratory_other_findings
        remove_column :doctor_examinations, :gastrointestinal_liver
        remove_column :doctor_examinations, :gastrointestinal_spleen
        remove_column :doctor_examinations, :gastrointestinal_swelling
        remove_column :doctor_examinations, :gastrointestinal_lymph_nodes
        remove_column :doctor_examinations, :gastrointestinal_rectal_examination
        remove_column :doctor_examinations, :gastrointestinal_other
        remove_column :doctor_examinations, :system_nervous_general_mental_status
        remove_column :doctor_examinations, :system_nervous_general_appearance
        remove_column :doctor_examinations, :system_nervous_speech_quality
        remove_column :doctor_examinations, :system_nervous_speech_coherent
        remove_column :doctor_examinations, :system_nervous_speech_relevant
        remove_column :doctor_examinations, :system_nervous_mood
        remove_column :doctor_examinations, :system_nervous_mood_depressed
        remove_column :doctor_examinations, :system_nervous_mood_depressed_feeling_down
        remove_column :doctor_examinations, :system_nervous_mood_depressed_lost_interest
        remove_column :doctor_examinations, :system_nervous_mood_anxious
        remove_column :doctor_examinations, :system_nervous_mood_irritable
        remove_column :doctor_examinations, :system_nervous_affect
        remove_column :doctor_examinations, :system_nervous_thought
        remove_column :doctor_examinations, :system_nervous_thought_delusion
        remove_column :doctor_examinations, :system_nervous_thought_suicidality
        remove_column :doctor_examinations, :system_nervous_thought_suicidality_worth_living
        remove_column :doctor_examinations, :system_nervous_thought_suicidality_ending_life
        remove_column :doctor_examinations, :system_nervous_perception
        remove_column :doctor_examinations, :system_nervous_orientation
        remove_column :doctor_examinations, :system_nervous_time
        remove_column :doctor_examinations, :system_nervous_place
        remove_column :doctor_examinations, :system_nervous_person
        remove_column :doctor_examinations, :system_nervous_speech
        remove_column :doctor_examinations, :system_nervous_cognitive_function
        remove_column :doctor_examinations, :system_nervous_size_of_peripheral_nerves
        remove_column :doctor_examinations, :system_nervous_motor_power
        remove_column :doctor_examinations, :system_nervous_sensory
        remove_column :doctor_examinations, :system_nervous_reflexes
        remove_column :doctor_examinations, :system_nervous_other
        remove_column :doctor_examinations, :system_genitourinary_kidney
        remove_column :doctor_examinations, :system_genitourinary_discharge
        remove_column :doctor_examinations, :system_genitourinary_sores_ulcers
        remove_column :doctor_examinations, :system_breast_abnormal_discharge
        remove_column :doctor_examinations, :system_breast_lump
        remove_column :doctor_examinations, :system_breast_axillary_lympth_node
        remove_column :doctor_examinations, :system_breast_other
        remove_column :doctor_examinations, :system_comment
        remove_column :doctor_examinations, :condition_hiv
        remove_column :doctor_examinations, :condition_tuberculosis
        remove_column :doctor_examinations, :condition_malaria
        remove_column :doctor_examinations, :condition_leprosy
        remove_column :doctor_examinations, :condition_std
        remove_column :doctor_examinations, :condition_hepatitis
        remove_column :doctor_examinations, :condition_cancer
        remove_column :doctor_examinations, :condition_epilepsy
        remove_column :doctor_examinations, :condition_psychiatric_disorder
        remove_column :doctor_examinations, :condition_other
        remove_column :doctor_examinations, :condition_hypertension
        remove_column :doctor_examinations, :condition_heart_diseases
        remove_column :doctor_examinations, :condition_bronchial_asthma
        remove_column :doctor_examinations, :condition_diabetes_mellitus
        remove_column :doctor_examinations, :condition_peptic_ulcer
        remove_column :doctor_examinations, :condition_kidney_diseases
        remove_column :doctor_examinations, :condition_urine_for_pregnant
        remove_column :doctor_examinations, :condition_urine_for_opiates
        remove_column :doctor_examinations, :condition_urine_for_cannabis
        remove_column :doctor_examinations, :certification_comment
        remove_column :doctor_examinations, :unsuitable_comment
        remove_column :doctor_examinations, :notified_health_office
        remove_column :doctor_examinations, :notified_health_office_date
        remove_column :doctor_examinations, :referred_to_government_hospital
        remove_column :doctor_examinations, :referred_to_government_hospital_date
        remove_column :doctor_examinations, :referred_to_private_hospital
        remove_column :doctor_examinations, :referred_to_private_hospital_date
        remove_column :doctor_examinations, :treating_patient
        remove_column :doctor_examinations, :treating_patient_date
        remove_column :doctor_examinations, :undergoing_treatment
        remove_column :doctor_examinations, :undergoing_treatment_date

        remove_column :laboratory_examinations, :blood_group_other
        remove_column :laboratory_examinations, :blood_group_rhesus_other
        remove_column :laboratory_examinations, :elisa
        remove_column :laboratory_examinations, :hbsag
        remove_column :laboratory_examinations, :vdrl
        remove_column :laboratory_examinations, :tpha
        remove_column :laboratory_examinations, :malaria
        remove_column :laboratory_examinations, :bfmp
        remove_column :laboratory_examinations, :opiates
        remove_column :laboratory_examinations, :cannabis
        remove_column :laboratory_examinations, :pregnancy
        remove_column :laboratory_examinations, :pregnancy_serum_beta_hcg
        remove_column :laboratory_examinations, :sugar
        remove_column :laboratory_examinations, :sugar_value
        remove_column :laboratory_examinations, :albumin
        remove_column :laboratory_examinations, :albumin_value
        remove_column :laboratory_examinations, :abnormal_reason
        remove_column :laboratory_examinations, :laboratory_report_date

        remove_column :xray_examinations, :thoracic_cage
        remove_column :xray_examinations, :thoracic_cage_comment
        remove_column :xray_examinations, :heart_shape_and_size
        remove_column :xray_examinations, :heart_shape_and_size_comment
        remove_column :xray_examinations, :lung_fields
        remove_column :xray_examinations, :lung_fields_comment
        remove_column :xray_examinations, :mediastinum_and_hila
        remove_column :xray_examinations, :mediastinum_and_hila_comment
        remove_column :xray_examinations, :pleura_hemidiaphragms_costopherenic_angles
        remove_column :xray_examinations, :pleura_hemidiaphragms_costopherenic_angles_comment
        remove_column :xray_examinations, :focal_lesion
        remove_column :xray_examinations, :focal_lesion_comment
        remove_column :xray_examinations, :other_findings
        remove_column :xray_examinations, :other_findings_comment
        remove_column :xray_examinations, :impression

        remove_column :medical_examinations, :history_hiv
        remove_column :medical_examinations, :history_hiv_date
        remove_column :medical_examinations, :history_tuberculosis
        remove_column :medical_examinations, :history_tuberculosis_date
        remove_column :medical_examinations, :history_leprosy
        remove_column :medical_examinations, :history_leprosy_date
        remove_column :medical_examinations, :history_viral_hepatitis
        remove_column :medical_examinations, :history_viral_hepatitis_date
        remove_column :medical_examinations, :history_psychiatric_illness
        remove_column :medical_examinations, :history_psychiatric_illness_date
        remove_column :medical_examinations, :history_epilepsy
        remove_column :medical_examinations, :history_epilepsy_date
        remove_column :medical_examinations, :history_cancer
        remove_column :medical_examinations, :history_cancer_date
        remove_column :medical_examinations, :history_std
        remove_column :medical_examinations, :history_std_date
        remove_column :medical_examinations, :history_malaria
        remove_column :medical_examinations, :history_malaria_date
        remove_column :medical_examinations, :history_hypertension
        remove_column :medical_examinations, :history_hypertension_date
        remove_column :medical_examinations, :history_heart_diseases
        remove_column :medical_examinations, :history_heart_diseases_date
        remove_column :medical_examinations, :history_bronchial_asthma
        remove_column :medical_examinations, :history_bronchial_asthma_date
        remove_column :medical_examinations, :history_diabetes_mellitus
        remove_column :medical_examinations, :history_diabetes_mellitus_date
        remove_column :medical_examinations, :history_peptic_ulcer
        remove_column :medical_examinations, :history_peptic_ulcer_date
        remove_column :medical_examinations, :history_kidney_diseases
        remove_column :medical_examinations, :history_kidney_diseases_date
        remove_column :medical_examinations, :history_other
        remove_column :medical_examinations, :history_other_date
        remove_column :medical_examinations, :history_taken_drug_recently
        remove_column :medical_examinations, :history_comment
        remove_column :medical_examinations, :physical_chronic_skin_rash
        remove_column :medical_examinations, :physical_anaesthetic_skin_patch
        remove_column :medical_examinations, :physical_deformities_of_limbs
        remove_column :medical_examinations, :physical_pallor
        remove_column :medical_examinations, :physical_jaundice
        remove_column :medical_examinations, :physical_lymph_node_enlargement
        remove_column :medical_examinations, :physical_vision_test_unaided_left
        remove_column :medical_examinations, :physical_vision_test_unaided_right
        remove_column :medical_examinations, :physical_vision_test_aided_left
        remove_column :medical_examinations, :physical_vision_test_aided_right
        remove_column :medical_examinations, :physical_hearing_ability_left
        remove_column :medical_examinations, :physical_hearing_ability_right
        remove_column :medical_examinations, :physical_other
        remove_column :medical_examinations, :physical_comment
        remove_column :medical_examinations, :system_cardiovascular_heart_size
        remove_column :medical_examinations, :system_cardiovascular_heart_sounds
        remove_column :medical_examinations, :system_cardiovascular_other_findings
        remove_column :medical_examinations, :system_respiratory_breath_sounds
        remove_column :medical_examinations, :system_respiratory_other_findings
        remove_column :medical_examinations, :gastrointestinal_liver
        remove_column :medical_examinations, :gastrointestinal_spleen
        remove_column :medical_examinations, :gastrointestinal_swelling
        remove_column :medical_examinations, :gastrointestinal_lymph_nodes
        remove_column :medical_examinations, :gastrointestinal_rectal_examination
        remove_column :medical_examinations, :gastrointestinal_other
        remove_column :medical_examinations, :system_nervous_general_mental_status
        remove_column :medical_examinations, :system_nervous_general_appearance
        remove_column :medical_examinations, :system_nervous_speech_quality
        remove_column :medical_examinations, :system_nervous_speech_coherent
        remove_column :medical_examinations, :system_nervous_speech_relevant
        remove_column :medical_examinations, :system_nervous_mood
        remove_column :medical_examinations, :system_nervous_mood_depressed
        remove_column :medical_examinations, :system_nervous_mood_depressed_feeling_down
        remove_column :medical_examinations, :system_nervous_mood_depressed_lost_interest
        remove_column :medical_examinations, :system_nervous_mood_anxious
        remove_column :medical_examinations, :system_nervous_mood_irritable
        remove_column :medical_examinations, :system_nervous_affect
        remove_column :medical_examinations, :system_nervous_thought
        remove_column :medical_examinations, :system_nervous_thought_delusion
        remove_column :medical_examinations, :system_nervous_thought_suicidality
        remove_column :medical_examinations, :system_nervous_thought_suicidality_worth_living
        remove_column :medical_examinations, :system_nervous_thought_suicidality_ending_life
        remove_column :medical_examinations, :system_nervous_perception
        remove_column :medical_examinations, :system_nervous_orientation
        remove_column :medical_examinations, :system_nervous_time
        remove_column :medical_examinations, :system_nervous_place
        remove_column :medical_examinations, :system_nervous_person
        remove_column :medical_examinations, :system_nervous_speech
        remove_column :medical_examinations, :system_nervous_cognitive_function
        remove_column :medical_examinations, :system_nervous_size_of_peripheral_nerves
        remove_column :medical_examinations, :system_nervous_motor_power
        remove_column :medical_examinations, :system_nervous_sensory
        remove_column :medical_examinations, :system_nervous_reflexes
        remove_column :medical_examinations, :system_nervous_other
        remove_column :medical_examinations, :system_genitourinary_kidney
        remove_column :medical_examinations, :system_genitourinary_discharge
        remove_column :medical_examinations, :system_genitourinary_sores_ulcers
        remove_column :medical_examinations, :system_breast_abnormal_discharge
        remove_column :medical_examinations, :system_breast_lump
        remove_column :medical_examinations, :system_breast_axillary_lympth_node
        remove_column :medical_examinations, :system_breast_other
        remove_column :medical_examinations, :system_comment
        remove_column :medical_examinations, :condition_hiv
        remove_column :medical_examinations, :condition_tuberculosis
        remove_column :medical_examinations, :condition_malaria
        remove_column :medical_examinations, :condition_leprosy
        remove_column :medical_examinations, :condition_std
        remove_column :medical_examinations, :condition_hepatitis
        remove_column :medical_examinations, :condition_cancer
        remove_column :medical_examinations, :condition_epilepsy
        remove_column :medical_examinations, :condition_psychiatric_disorder
        remove_column :medical_examinations, :condition_other
        remove_column :medical_examinations, :condition_hypertension
        remove_column :medical_examinations, :condition_heart_diseases
        remove_column :medical_examinations, :condition_bronchial_asthma
        remove_column :medical_examinations, :condition_diabetes_mellitus
        remove_column :medical_examinations, :condition_peptic_ulcer
        remove_column :medical_examinations, :condition_kidney_diseases
        remove_column :medical_examinations, :condition_urine_for_pregnant
        remove_column :medical_examinations, :condition_urine_for_opiates
        remove_column :medical_examinations, :condition_urine_for_cannabis
        remove_column :medical_examinations, :certification_comment
        remove_column :medical_examinations, :unsuitable_comment
        remove_column :medical_examinations, :notified_health_office
        remove_column :medical_examinations, :notified_health_office_date
        remove_column :medical_examinations, :referred_to_government_hospital
        remove_column :medical_examinations, :referred_to_government_hospital_date
        remove_column :medical_examinations, :referred_to_private_hospital
        remove_column :medical_examinations, :referred_to_private_hospital_date
        remove_column :medical_examinations, :treating_patient
        remove_column :medical_examinations, :treating_patient_date
        remove_column :medical_examinations, :undergoing_treatment
        remove_column :medical_examinations, :undergoing_treatment_date
        remove_column :medical_examinations, :previous_review
    end
end