class XrayReviewsNormalizeClean < ActiveRecord::Migration[6.0]
    def change
        remove_column :xray_reviews, :is_id_incomplete, :string
        remove_column :xray_reviews, :is_id_wrong, :string
        remove_column :xray_reviews, :is_id_not_clear, :string
        remove_column :xray_reviews, :is_id_not_printed, :string
        remove_column :xray_reviews, :is_proc_chemical_defect, :string
        remove_column :xray_reviews, :is_proc_marks_of_film, :string
        remove_column :xray_reviews, :is_proc_fog, :string
        remove_column :xray_reviews, :is_proc_screen_defect, :string
        remove_column :xray_reviews, :is_pos_roi_cut_off, :string
        remove_column :xray_reviews, :is_pos_roi_not_clearly_visualized, :string
        remove_column :xray_reviews, :is_pos_collimation, :string
        remove_column :xray_reviews, :is_pos_scapular_not_retracted, :string
        remove_column :xray_reviews, :is_pos_poor_inspiratory_effort, :string
        remove_column :xray_reviews, :is_exp_overexposure, :string
        remove_column :xray_reviews, :is_exp_underexposure, :string
        remove_column :xray_reviews, :is_arti_processing_artifacts, :string
        remove_column :xray_reviews, :is_arti_poor_handling_artifacts, :string
        remove_column :xray_reviews, :is_super_same_thoracic_cage, :string
        remove_column :xray_reviews, :is_super_different_thoracic_cage, :string
        remove_column :xray_reviews, :is_pam_wrong_placement, :string
        remove_column :xray_reviews, :is_pam_not_available, :string
        remove_column :xray_reviews, :is_blur_movement, :string
        remove_column :xray_reviews, :is_blur_breathing, :string
        remove_column :xray_reviews, :is_improper_report, :string
        remove_column :xray_reviews, :is_no_diagnostic_value, :string
        remove_column :xray_reviews, :taken_by, :string
        remove_column :xray_reviews, :reported_by, :string
        remove_column :xray_reviews, :is_id_not_available, :string
        remove_column :xray_reviews, :id_incomplete_clinic_name, :string
        remove_column :xray_reviews, :id_incomplete_worker_name, :string
        remove_column :xray_reviews, :id_incomplete_transaction_id, :string
        remove_column :xray_reviews, :id_incomplete_xray_taken_date, :string
        remove_column :xray_reviews, :id_not_clear_blur, :string
        remove_column :xray_reviews, :id_not_clear_fog, :string
        remove_column :xray_reviews, :id_not_clear_dark, :string
        remove_column :xray_reviews, :id_not_printed_handwritten, :string
        remove_column :xray_reviews, :id_not_printed_sticker, :string
        remove_column :xray_reviews, :proc_chemical_defect_weak_chemical, :string
        remove_column :xray_reviews, :proc_chemical_defect_discoloration, :string
        remove_column :xray_reviews, :proc_chemical_defect_stain, :string
        remove_column :xray_reviews, :proc_chemical_defect_water_mark, :string
        remove_column :xray_reviews, :proc_chemical_defect_poor_agitation, :string
        remove_column :xray_reviews, :proc_marks_of_film_film_guide_mark, :string
        remove_column :xray_reviews, :proc_marks_of_film_scratches, :string
        remove_column :xray_reviews, :proc_fog_partial_fog, :string
        remove_column :xray_reviews, :proc_fog_base_fog, :string
        remove_column :xray_reviews, :proc_screen_defect_dirty_screen, :string
        remove_column :xray_reviews, :proc_screen_defect_spoilt_screen, :string
        remove_column :xray_reviews, :id_wrong_clinic_name, :string
        remove_column :xray_reviews, :id_wrong_worker_name, :string
        remove_column :xray_reviews, :id_wrong_transaction_id, :string
        remove_column :xray_reviews, :id_wrong_xray_taken_date, :string
        remove_column :xray_reviews, :pos_apices_cut, :string
        remove_column :xray_reviews, :pos_chest_wall_cut, :string
        remove_column :xray_reviews, :pos_cpa_cut, :string
        remove_column :xray_reviews, :pos_rotation, :string
        remove_column :xray_reviews, :pos_angulation, :string
        remove_column :xray_reviews, :pos_id_obscure_apex, :string
        remove_column :xray_reviews, :pos_marker_obscure_apex, :string
        remove_column :xray_reviews, :pos_poor_colimation, :string
        remove_column :xray_reviews, :pos_no_colimation, :string
        remove_column :xray_reviews, :is_improper_marking, :string
        remove_column :xray_reviews, :is_artifact, :string
        remove_column :xray_reviews, :is_blur, :string
        remove_column :xray_reviews, :is_marker_problem, :string
        remove_column :xray_reviews, :is_envelope_problem, :string
    end
end
