class Dashboards::GeographicalController < InternalController
    def index
       index_data       
    end
     
    def index_test 
       index_data
    end 

     def towns       
       id = JSON.parse( params.keys.first)["id"]
       state = State.where('name=?',id).pluck(:id) rescue nil       
       @towns = Town.where("state_id=?",state).order("name Asc").pluck(:name,:id)
     end 
     
     def filter
       params = JSON.parse( params.keys.first)
     end  
     
    def index_data
        if request.format.js? 
            if(params.values.first!=nil)
              district JSON.parse(params.values.first)
            end 
         else
           @employer_count = Employer.count
           @doctor_count = Doctor.count
           @states_count = State.count
           @xray_facility_count = XrayFacility.count
           @xray_count = Laboratory.count
           @fw_worker = Transaction.count
           @detectdisease=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506','3507','3508','3509','3510','3511','3512','3513','3514','3515','3516','3517','3518','3519','3520')").count
           @dtectcommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506')").count
           @dtectnoncommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3507','3508','3509','3510','3511','3512','3514','3515','3516','3517','3518','3519','3520','3513') ").count
           @dtectcommunicabletuber=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501') ").count
           @dtectcommunicablehepa=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3502') ").count
           @dtectcommunicablesyphilis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3503') ").count
           @dtectcommunicablehiv=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3504')  ").count
           @dtectcommunicablemalaria=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3505') ").count
           @dtectcommunicableleprosy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3506') ").count
            
           @dtectnoncommunicablepreg=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3507') ").count
           @dtectnoncommunicableurine=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3508') ").count
           @dtectnoncommunicablecannabis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3509') ").count
           @dtectnoncommunicableillness=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3510') ").count
           @dtectnoncommunicableepilesy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3511') ").count
           @dtectnoncommunicablecancer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3512') ").count
           @dtectnoncommunicablehypertens=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3513') ").count
           @dtectnoncommunicablediabetes=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3514')").count
           @dtectnoncommunicablekidney=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3515')").count
           @dtectnoncommunicableheart=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3516')").count
           @dtectnoncommunicableulcer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3517')").count
           @dtectnoncommunicableasthama=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3518')").count
           @dtectnoncommunicableothers=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3519')").count

         end
         @states = State.order("name Asc").pluck(:id,:name)
         #@towns = Town.pluck(:name,:id)
    end
       
    def district filter_params
        if(filter_params=="SABAH")
           @doctor_count=Doctor.joins(:state).where("states.name=?",filter_params).count
           @doctorxray_count=XrayFacility.joins(:state).where("states.name=?",filter_params).count
           @doctorlab_count=Laboratory.joins(:state).where("states.name=?",filter_params).count           
         end
    end
   
    def filter filter_params
        if filter_params["state"] == "All" || filter_params["state"] == "Select State"
           @doctor_count = Doctor.count
           @states_count = State.count
           @xray_facility_count = XrayFacility.count
           @xray_count = Laboratory.count
           @fw_worker = Transaction.where("final_result_date = ?",Date.today).count
           @employer_count = Employer.count
        else
           filter_params["district"] = nil if filter_params["district"] == "Select District"
           filter_params["district"] = Town.ids if filter_params["district"] == "All"
           @doctor = Doctor.where("state_id = ? OR town_id = ?",filter_params["state"],filter_params["district"])
           @doctor_count = @doctor.count
        unless filter_params["dateRange"].nil?
           start_date_str, end_date_str = filter_params["dateRange"].split(' - ')
           # Parse the start_date and end_date as Date objects
           start_date = Date.strptime(start_date_str, '%d/%m/%Y')
           end_date = Date.strptime(end_date_str, '%d/%m/%Y')
           @fw_worker = @doctor.map{|i| i.transactions.where(transactions: {final_result_date: start_date..end_date}).count}.sum 
        else
           @fw_worker = @doctor.map{|i| i.transactions.where(transactions: {final_result_date: Date.new(Date.today.year, 1, 1)..Date.today}).count}.sum 
        end 
           @xray_facility_count = XrayFacility.where("state_id = ? OR town_id = ?",filter_params["state"],filter_params["district"]).count
           @xray_count = Laboratory.where("state_id = ? OR town_id = ?",filter_params["state"],filter_params["district"]).count
           @employer_count = Employer.where("state_id = ? OR town_id = ?",filter_params["state"],filter_params["district"]).count
           @states_count = State.where(id: filter_params["state"]).count
        end 
    end 
       
    def statevalues      
       foo = params[:districtname]
       @doctorsabah_count=Doctor.joins(:state).where("states.name=?",foo).count
       @doctorxray_count=XrayFacility.joins(:state).where("states.name=?",foo).count
       @doctorlab_count=Laboratory.joins(:state).where("states.name=?",foo).count
       @doctoremp_count=Employer.joins(:state).where("states.name=?",foo).count
       @doctorfw_count=ForeignWorker.joins(:state).where("states.name=?",foo).count
       @detectdisease=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506','3507','3508','3509','3510','3511','3512','3513','3514','3515','3516','3517','3518','3519','3520') and states.name=?",foo).count
       @dtectcommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506') and states.name=?",foo).count
       @dtectnoncommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3507','3508','3509','3510','3511','3512','3514','3515','3516','3517','3518','3519','3520','3513') and states.name=?",foo).count
       @dtectcommunicabletuber=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3501') and states.name=?",foo).count
       @dtectcommunicablehepa=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3502') and states.name=?",foo).count
       @dtectcommunicablesyphilis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3503') and states.name=?",foo).count
       @dtectcommunicablehiv=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3504')  and states.name=?",foo).count
       @dtectcommunicablemalaria=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3505') and states.name=?",foo).count
       @dtectcommunicableleprosy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3506') and states.name=?",foo).count
       
       @dtectnoncommunicablepreg=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3507') and states.name=?",foo).count
       @dtectnoncommunicableurine=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3508') and states.name=?",foo).count
       @dtectnoncommunicablecannabis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3509') and states.name=?",foo).count
       @dtectnoncommunicableillness=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3510') and states.name=?",foo).count
       @dtectnoncommunicableepilesy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3511') and states.name=?",foo).count
       @dtectnoncommunicablecancer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3512') and states.name=?",foo).count
       @dtectnoncommunicablehypertens=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3513') and states.name=?",foo).count
       @dtectnoncommunicablediabetes=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3514') and states.name=?",foo).count
       @dtectnoncommunicablekidney=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3515') and states.name=?",foo).count
       @dtectnoncommunicableheart=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3516') and states.name=?",foo).count
       @dtectnoncommunicableulcer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3517') and states.name=?",foo).count
       @dtectnoncommunicableasthama=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3518') and states.name=?",foo).count
       @dtectnoncommunicableothers=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join states on states.id=doctors.state_id").where("medical_examination_details.condition_id IN('3519') and states.name=?",foo).count
   
       render json:{"noofdoctors":@doctorsabah_count,"noofxray":@doctorxray_count,"nooflab":@doctorlab_count,"empcount":@doctoremp_count,"fwcount":@doctorfw_count,"detectdisease":@detectdisease,"commcount":@dtectcommunicable,"noncommcount":@dtectnoncommunicable,"tuberculosis":@dtectcommunicabletuber,"hepatisis":@dtectcommunicablehepa,"syphilis":@dtectcommunicablesyphilis,"hiv":@dtectcommunicablehiv,"malaria":@dtectcommunicablemalaria,"leporacy":@dtectcommunicableleprosy,"pregnancy":@dtectnoncommunicablepreg,"urine":@dtectnoncommunicableurine,"cannabis":@dtectnoncommunicablecannabis,"illness":@dtectnoncommunicableillness,"epilsey":@dtectnoncommunicableepilesy,"cancer":@dtectnoncommunicablecancer,"hypertension":@dtectnoncommunicablehypertens,"diabetes":@dtectnoncommunicablediabetes,"kidney":@dtectnoncommunicablediabetes,"heart":@dtectnoncommunicableheart,"ulcer":@dtectnoncommunicableulcer,"asthama":@dtectnoncommunicableasthama,"others":@dtectnoncommunicableothers}
    end

    def districtvalues
       foo = params[:districtvalue]
       @doctorsabah_count=Doctor.joins(:town).where("towns.name=?",foo).count
       @doctorxray_count=XrayFacility.joins(:town).where("towns.name=?",foo).count
       @doctorlab_count=Laboratory.joins(:town).where("towns.name=?",foo).count
       @doctoremp_count=Employer.joins(:town).where("towns.name=?",foo).count
       @doctorfw_count=ForeignWorker.joins(:town).where("towns.name=?",foo).count
       @detectdisease=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506','3507','3508','3509','3510','3511','3512','3513','3514','3515','3516','3517','3518','3519','3520') and towns.name=?",foo).count
       @dtectcommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3501','3502','3503','3504','3505','3506') and towns.name=?",foo).count
       @dtectnoncommunicable=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3507','3508','3509','3510','3511','3512','3514','3515','3516','3517','3518','3519','3520','3513') and towns.name=?",foo).count
       @dtectcommunicabletuber=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3501') and towns.name=?",foo).count
       @dtectcommunicablehepa=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3502') and towns.name=?",foo).count
       @dtectcommunicablesyphilis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3503') and towns.name=?",foo).count
       @dtectcommunicablehiv=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3504')  and towns.name=?",foo).count
       @dtectcommunicablemalaria=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3505') and towns.name=?",foo).count
       @dtectcommunicableleprosy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3506') and towns.name=?",foo).count
       
       @dtectnoncommunicablepreg=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3507') and towns.name=?",foo).count
       @dtectnoncommunicableurine=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3508') and towns.name=?",foo).count
       @dtectnoncommunicablecannabis=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3509') and towns.name=?",foo).count
       @dtectnoncommunicableillness=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3510') and towns.name=?",foo).count
       @dtectnoncommunicableepilesy=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3511') and towns.name=?",foo).count
       @dtectnoncommunicablecancer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3512') and towns.name=?",foo).count
       @dtectnoncommunicablehypertens=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3513') and towns.name=?",foo).count
       @dtectnoncommunicablediabetes=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3514') and towns.name=?",foo).count
       @dtectnoncommunicablekidney=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3515') and towns.name=?",foo).count
       @dtectnoncommunicableheart=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3516') and towns.name=?",foo).count
       @dtectnoncommunicableulcer=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3517') and towns.name=?",foo).count
       @dtectnoncommunicableasthama=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3518') and towns.name=?",foo).count
       @dtectnoncommunicableothers=Transaction.joins("join medical_examination_details on medical_examination_details.transaction_id=transactions.id").joins("join medical_examinations on medical_examinations.transaction_id=transactions.id").joins("join doctors on doctors.id=transactions.doctor_id").joins("join doctor_examination_details on doctor_examination_details.transaction_id=transactions.id").joins("join towns on towns.id=doctors.town_id").where("medical_examination_details.condition_id IN('3519') and towns.name=?",foo).count
          
       render json:{"noofdoctors":@doctorsabah_count,"noofxray":@doctorxray_count,"nooflab":@doctorlab_count,"empcount":@doctoremp_count,"fwcount":@doctorfw_count,"detectdisease":@detectdisease,"commcount":@dtectcommunicable,"noncommcount":@dtectnoncommunicable,"tuberculosis":@dtectcommunicabletuber,"hepatisis":@dtectcommunicablehepa,"syphilis":@dtectcommunicablesyphilis,"hiv":@dtectcommunicablehiv,"malaria":@dtectcommunicablemalaria,"leporacy":@dtectcommunicableleprosy,"pregnancy":@dtectnoncommunicablepreg,"urine":@dtectnoncommunicableurine,"cannabis":@dtectnoncommunicablecannabis,"illness":@dtectnoncommunicableillness,"epilsey":@dtectnoncommunicableepilesy,"cancer":@dtectnoncommunicablecancer,"hypertension":@dtectnoncommunicablehypertens,"diabetes":@dtectnoncommunicablediabetes,"kidney":@dtectnoncommunicablediabetes,"heart":@dtectnoncommunicableheart,"ulcer":@dtectnoncommunicableulcer,"asthama":@dtectnoncommunicableasthama,"others":@dtectnoncommunicableothers}
     end
   end
   